// Soalan Sains Darjah 5, sepuluh bab.

import { m, i } from './soalan.mjs';

export default [
  // ------------------------------------------------ 1. Kemahiran Saintifik
  {
    mudah: [
      m('Apakah maksud mengukur dalam sains?', ['Membandingkan sesuatu dengan unit piawai', 'Meneka nilainya', 'Melukis objek', 'Menamakan objek'], 0,
        'Mengukur bermaksud membandingkan kuantiti dengan unit yang dipersetujui.'),
      m('Apakah unit piawai bagi isi padu?', ['Liter', 'Kilogram', 'Meter', 'Saat'], 0,
        'Isi padu cecair diukur dalam liter atau mililiter.'),
      m('Apakah maksud pemboleh ubah bergerak balas?', ['Perkara yang diukur dalam eksperimen', 'Perkara yang diubah', 'Perkara yang dikekalkan', 'Perkara yang dibuang'], 0,
        'Pemboleh ubah bergerak balas ialah hasil yang kita perhati dan ukur.'),
      m('Apakah maksud membuat hipotesis?', ['Menyatakan jangkaan yang boleh diuji', 'Menyalin keputusan', 'Menulis kesimpulan awal', 'Membuang data'], 0,
        'Hipotesis ialah kenyataan yang boleh disemak melalui eksperimen.'),
      m('Alat manakah paling sesuai mengukur masa dalam eksperimen?', ['Jam randik', 'Termometer', 'Neraca', 'Silinder penyukat'], 0,
        'Jam randik mengukur tempoh dengan tepat.'),
      i('Berapa mililiter dalam 3.5 liter?', 3500,
        '3.5 × 1000 = 3500 ml.'),
      i('Berapa gram dalam 4.2 kilogram?', 4200,
        '4.2 × 1000 = 4200 g.'),
      m('Apakah kegunaan graf dalam laporan sains?', ['Menunjukkan corak dan hubungan dalam data', 'Menambah warna', 'Menggantikan eksperimen', 'Menyembunyikan keputusan'], 0,
        'Graf menjadikan corak dalam data lebih mudah dilihat.'),
      m('Apakah langkah terakhir dalam kaedah saintifik?', ['Membuat kesimpulan', 'Membuat hipotesis', 'Mengumpul alat', 'Menulis tajuk'], 0,
        'Kesimpulan dibuat selepas data dianalisis.'),
      m('Kenapa eksperimen perlu dijalankan dengan selamat?', ['Untuk mengelakkan kecederaan dan kerosakan', 'Untuk menjimatkan masa', 'Untuk mendapat markah', 'Untuk kelihatan kemas'], 0,
        'Keselamatan mesti didahulukan sebelum sebarang keputusan diperoleh.')
    ],
    sederhana: [
      i('Suhu air mula-mula 27 darjah. Selepas dipanaskan ia menjadi 94 darjah. Berapa darjah perbezaannya?', 67,
        '94 − 27 = 67 darjah.'),
      m('Rina menguji kesan jenis air terhadap pertumbuhan pokok. Apakah pemboleh ubah dimalarkan?', ['Saiz pasu dan jumlah cahaya', 'Jenis air', 'Tinggi pokok', 'Kadar pertumbuhan'], 0,
        'Semua faktor selain jenis air mesti dikekalkan sama.'),
      i('Purata jisim 8 objek ialah 45 g. Berapa gram jumlah jisim kesemuanya?', 360,
        '8 × 45 = 360 g.'),
      m('Kenapa bacaan silinder penyukat diambil pada paras mata?', ['Untuk mengelakkan bacaan yang terpesong', 'Supaya lebih cepat', 'Supaya lebih cantik', 'Supaya silinder tidak jatuh'], 0,
        'Melihat dari sudut lain menyebabkan paras cecair kelihatan berbeza.'),
      i('Sebuah eksperimen berulang 7 kali, setiap satu 8 minit. Berapa minit semuanya?', 56,
        '7 × 8 = 56 minit.'),
      m('Manakah kesimpulan yang disokong data jika pokok berbaja tumbuh 20 cm dan tanpa baja tumbuh 12 cm?', ['Baja meningkatkan pertumbuhan dalam ujian ini', 'Baja sesuai untuk semua tumbuhan', 'Baja menjadikan pokok cantik', 'Baja menghentikan penyakit'], 0,
        'Kesimpulan mesti terhad kepada apa yang benar-benar diukur.'),
      i('Isi padu batu dicari dengan kaedah sesaran. Paras air naik dari 240 ml kepada 315 ml. Berapa cm padu isi padu batu itu?', 75,
        '315 − 240 = 75 ml, iaitu 75 cm padu.'),
      m('Kenapa eksperimen menggunakan sekurang-kurangnya lima nilai berbeza bagi pemboleh ubah dimanipulasi?', ['Supaya corak hubungan dapat dilihat dengan jelas', 'Supaya lebih lama', 'Supaya lebih mahal', 'Supaya lebih sukar'], 0,
        'Dua titik sahaja tidak mencukupi untuk menunjukkan bentuk hubungan.'),
      m('Apakah yang ditunjukkan graf garis yang menaik secara sekata?', ['Kedua-dua pemboleh ubah bertambah bersama secara tetap', 'Tiada hubungan', 'Satu bertambah dan satu berkurang', 'Data tidak sah'], 0,
        'Garis lurus menaik menunjukkan hubungan yang berkadar.'),
      i('Jisim bekas dan pasir ialah 1250 g. Jisim bekas kosong 380 g. Berapa gram jisim pasir itu?', 870,
        '1250 − 380 = 870 g.')
    ],
    cabaran: [
      i('Sebuah tangki berisi 5 liter air. Sebanyak 1250 ml digunakan tiga kali. Berapa ml air yang tinggal?', 1250,
        '3 × 1250 = 3750 ml digunakan. 5000 − 3750 = 1250 ml.'),
      m('Dua kumpulan mendapat keputusan berbeza dalam eksperimen yang sama. Apakah langkah pertama yang paling saintifik?', ['Bandingkan kaedah kedua-dua kumpulan', 'Terima keputusan yang lebih baik', 'Ulang kaedah yang gagal sahaja', 'Buang kedua-dua keputusan'], 0,
        'Perbezaan biasanya berpunca daripada perbezaan kaedah atau kawalan.'),
      i('Suhu turun secara sekata daripada 80 darjah kepada 32 darjah dalam 16 minit. Berapa darjah penurunan setiap minit?', 3,
        '80 − 32 = 48. 48 ÷ 16 = 3 darjah setiap minit.'),
      m('Kenapa kesimpulan tidak boleh melangkaui data yang dikumpul?', ['Kerana tiada bukti untuk keadaan yang tidak diuji', 'Kerana data terlalu banyak', 'Kerana guru melarang', 'Kerana graf terlalu kecil'], 0,
        'Dakwaan yang melebihi data bukan lagi kesimpulan saintifik.'),
      i('Purata lima bacaan ialah 62. Empat bacaan pertama ialah 58, 60, 64 dan 65. Berapakah bacaan kelima?', 63,
        'Jumlah = 5 × 62 = 310. 310 − 247 = 63.'),
      m('Apakah kelemahan eksperimen yang hanya menggunakan satu sampel?', ['Keputusan mungkin tidak mewakili keadaan sebenar', 'Sampel terlalu besar', 'Data terlalu banyak', 'Masa terlalu lama'], 0,
        'Satu sampel boleh luar biasa dan mengelirukan.'),
      i('Sebuah bikar berisi 480 ml air. Air itu dibahagi sama rata kepada 6 tabung uji. Berapa ml dalam setiap tabung?', 80,
        '480 ÷ 6 = 80 ml.'),
      m('Kenapa saintis menggunakan alat digital untuk ukuran yang sangat kecil?', ['Ia memberi bacaan yang lebih tepat dan konsisten', 'Ia lebih murah', 'Ia lebih cantik', 'Ia lebih besar'], 0,
        'Ketepatan alat menentukan kualiti data yang boleh dikumpul.'),
      m('Sebuah graf menunjukkan titik yang jauh terpisah daripada corak lain. Apakah namanya?', ['Data terpencil yang perlu disemak', 'Data purata', 'Data terbaik', 'Data kawalan'], 0,
        'Titik terpencil disemak semula sebelum diterima atau ditolak.'),
      i('Sebuah eksperimen mencatat 12 g, 15 g, 18 g, 11 g dan 14 g. Berapa gram puratanya?', 14,
        '12 + 15 + 18 + 11 + 14 = 70. 70 ÷ 5 = 14 g.')
    ],
    ultra: [
      i('Jisim 250 ml cecair ialah 300 g. Berapakah jisim 1 liter cecair yang sama dalam gram?', 1200,
        '1 liter = 4 × 250 ml, jadi 4 × 300 = 1200 g.'),
      m('Kenapa hubungan yang kelihatan pada graf tidak semestinya bermakna satu perkara menyebabkan yang lain?', ['Faktor ketiga yang tidak diukur mungkin mempengaruhi kedua-duanya', 'Graf sentiasa salah', 'Data tidak boleh dipercayai', 'Hubungan tidak wujud'], 0,
        'Kaitan dan sebab bukan perkara yang sama.'),
      i('Sebuah eksperimen mengukur pertumbuhan 2.5 cm setiap 4 hari. Berapa cm pertumbuhan dalam 28 hari?', 17.5,
        '28 ÷ 4 = 7 tempoh. 7 × 2.5 = 17.5 cm.'),
      m('Apakah tujuan sebenar mengulang eksperimen oleh saintis lain di tempat lain?', ['Menyemak sama ada keputusan itu benar dan bukan kebetulan tempatan', 'Menambah bilangan kertas kajian', 'Menjimatkan kos', 'Mencari kesilapan orang lain'], 0,
        'Keputusan yang boleh diulang di mana-mana lebih dipercayai.'),
      i('Sebuah bekas berisi 2 liter 400 ml air. Sebanyak 15 peratus tersejat. Berapa ml air yang tersejat?', 360,
        '2400 × 15 ÷ 100 = 360 ml.'),
      m('Kenapa saintis melaporkan had ketidakpastian dalam ukuran mereka?', ['Setiap alat mempunyai batas ketepatan yang perlu diketahui pembaca', 'Untuk menjadikan laporan panjang', 'Untuk mengelak tanggungjawab', 'Untuk menyembunyikan data'], 0,
        'Nombor tanpa had ketepatan boleh disalah tafsir sebagai lebih tepat daripada sebenarnya.'),
      i('Purata suhu tujuh hari ialah 31 darjah. Enam hari pertama berjumlah 184 darjah. Berapa darjah suhu hari ketujuh?', 33,
        'Jumlah = 7 × 31 = 217. 217 − 184 = 33 darjah.'),
      m('Sebuah eksperimen menunjukkan keputusan yang bertentangan dengan hipotesis. Apakah nilai keputusan itu?', ['Ia tetap memberi maklumat penting tentang keadaan sebenar', 'Ia tidak berguna', 'Ia mesti dibuang', 'Ia bermakna eksperimen gagal'], 0,
        'Hipotesis yang ditolak menyempitkan kemungkinan dan memandu kajian seterusnya.'),
      i('Sebuah bikar kehilangan 8 ml air setiap 15 minit melalui penyejatan. Berapa ml hilang dalam 2 jam?', 64,
        '2 jam = 120 minit. 120 ÷ 15 = 8 tempoh. 8 × 8 = 64 ml.'),
      m('Apakah perbezaan antara ketepatan dan kejituan dalam pengukuran?', ['Ketepatan menghampiri nilai sebenar manakala kejituan bermakna bacaan berulang hampir sama', 'Kedua-duanya sama', 'Ketepatan bermakna cepat', 'Kejituan bermakna murah'], 0,
        'Satu set bacaan boleh jitu tetapi tersasar jauh daripada nilai sebenar.')
    ]
  },

  // ------------------------------------------------------------ 2. Manusia
  {
    mudah: [
      m('Apakah organ utama dalam sistem pernafasan manusia?', ['Peparu', 'Jantung', 'Hati', 'Ginjal'], 0,
        'Peparu menjalankan pertukaran gas antara udara dan darah.'),
      m('Gas manakah diambil semasa kita menarik nafas?', ['Oksigen', 'Karbon dioksida', 'Nitrogen sahaja', 'Wap air sahaja'], 0,
        'Badan mengambil oksigen untuk membebaskan tenaga.'),
      m('Gas manakah dibebaskan semasa kita menghembus nafas?', ['Karbon dioksida', 'Oksigen sahaja', 'Nitrogen sahaja', 'Helium'], 0,
        'Karbon dioksida ialah bahan buangan proses pernafasan sel.'),
      m('Apakah organ yang menapis darah dan menghasilkan air kencing?', ['Ginjal', 'Peparu', 'Jantung', 'Usus'], 0,
        'Ginjal membuang bahan kumuh larut air daripada darah.'),
      m('Apakah organ yang mengepam darah ke seluruh badan?', ['Jantung', 'Peparu', 'Ginjal', 'Otak'], 0,
        'Jantung ialah pam yang mengedarkan darah.'),
      m('Apakah maksud perkumuhan pada manusia?', ['Membuang bahan kumuh yang terhasil daripada proses badan', 'Membuang tinja sahaja', 'Mengambil makanan', 'Menyimpan tenaga'], 0,
        'Bahan kumuh terhasil daripada tindak balas di dalam sel.'),
      m('Apakah maksud penyahtinjaan?', ['Membuang sisa makanan yang tidak dicerna', 'Membuang air kencing', 'Berpeluh', 'Bernafas'], 0,
        'Penyahtinjaan membuang bahan yang tidak pernah masuk ke dalam sel badan.'),
      m('Organ manakah membuang bahan kumuh melalui peluh?', ['Kulit', 'Peparu', 'Ginjal', 'Usus'], 0,
        'Kulit membuang air, garam dan sedikit urea melalui peluh.'),
      m('Kenapa kita perlu minum air yang cukup?', ['Untuk membantu ginjal membuang bahan kumuh', 'Untuk menambah berat', 'Untuk menyejukkan tulang', 'Untuk menambah tenaga terus'], 0,
        'Air diperlukan untuk melarutkan dan mengeluarkan bahan kumuh.'),
      m('Apakah tabiat yang merosakkan peparu?', ['Merokok', 'Bersenam', 'Minum air', 'Tidur cukup'], 0,
        'Asap rokok merosakkan tisu peparu secara kekal.')
    ],
    sederhana: [
      m('Kenapa kadar pernafasan meningkat semasa berlari?', ['Otot memerlukan lebih banyak oksigen dan membuang lebih banyak karbon dioksida', 'Badan menjadi lebih ringan', 'Peparu menjadi lebih besar kekal', 'Jantung berhenti sekejap'], 0,
        'Aktiviti yang berat meningkatkan keperluan tenaga.'),
      m('Kenapa kita berpeluh semasa cuaca panas?', ['Penyejatan peluh menyejukkan badan', 'Peluh memanaskan badan', 'Peluh menambah tenaga', 'Peluh menyimpan air'], 0,
        'Air yang tersejat membawa haba keluar dari kulit.'),
      m('Apakah kesan tidak membuang air kencing untuk masa yang lama?', ['Bahan kumuh terkumpul dan boleh menyebabkan jangkitan', 'Badan menjadi lebih kuat', 'Ginjal berehat', 'Tiada kesan'], 0,
        'Air kencing yang tertahan menjadi tempat pembiakan kuman.'),
      m('Kenapa udara yang dihembus keluar mengandungi lebih banyak wap air?', ['Permukaan dalam peparu lembap dan air tersejat ke dalam udara', 'Udara membawa air dari perut', 'Wap terhasil dari darah terus', 'Udara luar kering sepenuhnya'], 0,
        'Udara menjadi lembap semasa melalui saluran pernafasan.'),
      m('Apakah kesan pencemaran udara terhadap sistem pernafasan?', ['Zarah halus mengganggu peparu dan menyebabkan sesak nafas', 'Peparu menjadi lebih kuat', 'Pernafasan menjadi lebih perlahan', 'Tiada kesan'], 0,
        'Habuk dan asap mencetuskan keradangan saluran udara.'),
      m('Kenapa orang yang sakit ginjal perlu mengehadkan pengambilan garam?', ['Ginjal yang lemah sukar membuang lebihan garam', 'Garam menyebabkan rasa dahaga sahaja', 'Garam menambah tenaga', 'Garam merosakkan peparu'], 0,
        'Beban tambahan pada ginjal memburukkan keadaannya.'),
      m('Apakah fungsi bulu hidung dalam sistem pernafasan?', ['Menapis habuk sebelum udara masuk ke peparu', 'Menghangatkan darah', 'Menghasilkan oksigen', 'Membuang karbon dioksida'], 0,
        'Penapisan awal melindungi saluran udara yang lebih dalam.'),
      m('Kenapa senaman kerap baik untuk sistem pernafasan?', ['Ia meningkatkan kecekapan peparu dan jantung', 'Ia mengecilkan peparu', 'Ia mengurangkan keperluan oksigen', 'Ia menghentikan peluh'], 0,
        'Latihan berkala menjadikan pengangkutan oksigen lebih berkesan.'),
      m('Apakah yang berlaku kepada makanan yang tidak dicerna?', ['Ia dibuang melalui penyahtinjaan', 'Ia disimpan dalam ginjal', 'Ia menjadi darah', 'Ia menjadi peluh'], 0,
        'Sisa yang tidak diserap dikeluarkan melalui usus besar.'),
      m('Kenapa berpeluh banyak tanpa minum air berbahaya?', ['Badan kehilangan air dan garam sehingga boleh mengalami dehidrasi', 'Badan menjadi terlalu berat', 'Peluh menambah garam', 'Peparu berhenti'], 0,
        'Kehilangan cecair mesti diganti untuk mengekalkan fungsi badan.')
    ],
    cabaran: [
      m('Kenapa seorang perokok mudah cepat penat semasa bersukan?', ['Peparu yang rosak mengurangkan pengambilan oksigen', 'Otot menjadi lebih besar', 'Jantung berhenti', 'Darah menjadi lebih banyak'], 0,
        'Kurang oksigen bermakna otot tidak dapat menghasilkan tenaga dengan cukup cepat.'),
      m('Apakah kaitan antara sistem pernafasan dan sistem peredaran darah?', ['Darah mengangkut oksigen dari peparu ke seluruh badan', 'Kedua-duanya tidak berkaitan', 'Peparu mengepam darah', 'Jantung menapis udara'], 0,
        'Kedua-dua sistem bekerja bersama untuk membekalkan oksigen kepada sel.'),
      m('Kenapa pesakit ginjal perlu menjalani dialisis?', ['Mesin menapis darah menggantikan fungsi ginjal', 'Mesin menambah darah', 'Mesin memberi oksigen', 'Mesin memberi makanan'], 0,
        'Tanpa penapisan, bahan kumuh terkumpul sehingga membahayakan nyawa.'),
      m('Kenapa bernafas melalui hidung lebih baik daripada melalui mulut?', ['Hidung menapis, menghangatkan dan melembapkan udara', 'Mulut lebih kecil', 'Hidung lebih cepat', 'Mulut tiada saluran'], 0,
        'Udara yang disediakan dengan baik mengurangkan gangguan pada peparu.'),
      m('Apakah kesan bekerja lama di kawasan berhabuk tanpa topeng?', ['Zarah halus terkumpul dalam peparu dan merosakkannya', 'Peparu menjadi lebih kuat', 'Pernafasan menjadi lebih dalam kekal', 'Tiada kesan jangka panjang'], 0,
        'Kerosakan berlaku secara perlahan dan sering tidak disedari pada awalnya.'),
      m('Kenapa air kencing menjadi lebih pekat apabila kita kurang minum?', ['Ginjal menjimatkan air dengan mengurangkan kandungan cecair', 'Bahan kumuh bertambah', 'Ginjal berhenti berfungsi', 'Badan menghasilkan lebih banyak garam'], 0,
        'Ginjal mengimbangi antara membuang bahan kumuh dan menyimpan air.'),
      m('Apakah kesan udara sejuk dan kering terhadap saluran pernafasan?', ['Ia boleh mengeringkan dan merengsakan saluran udara', 'Ia menguatkan peparu', 'Ia menambah oksigen', 'Ia melembapkan peparu'], 0,
        'Itulah sebabnya sesetengah orang batuk lebih kerap dalam bilik berhawa dingin.'),
      m('Kenapa atlet berlatih di kawasan tanah tinggi?', ['Udara nipis melatih badan mengangkut oksigen dengan lebih cekap', 'Kawasan itu lebih sejuk sahaja', 'Latihan menjadi lebih mudah', 'Oksigen lebih banyak di situ'], 0,
        'Badan bertindak balas dengan menghasilkan lebih banyak sel darah merah.'),
      m('Apakah hubungan antara pengambilan air dan kesihatan ginjal jangka panjang?', ['Air yang cukup mengurangkan risiko batu karang dan jangkitan', 'Air merosakkan ginjal', 'Air tidak berkaitan', 'Air menggantikan ginjal'], 0,
        'Air melarutkan mineral supaya ia tidak mengkristal dalam ginjal.'),
      m('Kenapa asap rokok berbahaya juga kepada orang di sekeliling?', ['Asap yang disedut secara pasif mengandungi bahan berbahaya yang sama', 'Asap hanya berbahaya kepada perokok', 'Asap hilang serta-merta', 'Asap menjadi selamat di udara'], 0,
        'Perokok pasif turut menyedut bahan kimia toksik dalam asap.')
    ],
    ultra: [
      m('Kenapa keracunan karbon monoksida berbahaya walaupun oksigen ada dalam udara?', ['Karbon monoksida mengikat sel darah merah dan menghalang pengangkutan oksigen', 'Ia mengeringkan peparu', 'Ia memanaskan darah', 'Ia menutup hidung'], 0,
        'Darah tidak lagi dapat membawa oksigen walaupun bernafas seperti biasa.'),
      m('Apakah kesan gabungan merokok dan bekerja di kawasan tercemar?', ['Risiko penyakit peparu meningkat jauh lebih tinggi daripada satu faktor sahaja', 'Kedua-duanya membatalkan kesan', 'Risiko tidak berubah', 'Peparu menjadi kebal'], 0,
        'Kesan dua faktor berbahaya boleh menggandakan kerosakan.'),
      m('Kenapa badan menghasilkan lebih banyak air kencing selepas minum minuman berkafein?', ['Kafein meningkatkan pengeluaran air kencing oleh ginjal', 'Kafein menambah air dalam darah', 'Kafein merosakkan ginjal', 'Kafein menghentikan peluh'], 0,
        'Ini boleh menyebabkan kehilangan cecair jika tidak diganti.'),
      m('Apakah maksud bahawa peparu mempunyai luas permukaan yang sangat besar?', ['Banyak kantung udara kecil meningkatkan kadar pertukaran gas', 'Peparu sangat berat', 'Peparu memenuhi seluruh dada', 'Peparu menyerap makanan'], 0,
        'Luas permukaan yang besar membolehkan oksigen masuk ke darah dengan cepat.'),
      m('Kenapa kegagalan ginjal boleh membawa maut jika tidak dirawat?', ['Bahan kumuh dan lebihan cecair terkumpul sehingga meracuni badan', 'Badan kehilangan darah', 'Peparu berhenti serta-merta', 'Tulang menjadi lemah sahaja'], 0,
        'Ginjal mengawal keseimbangan kimia darah yang penting untuk semua organ.'),
      m('Apakah hubungan antara pernafasan sel dan pernafasan yang kita lihat?', ['Pernafasan luaran membekalkan oksigen untuk pernafasan sel yang menghasilkan tenaga', 'Kedua-duanya sama', 'Pernafasan sel berlaku dalam peparu sahaja', 'Pernafasan sel tidak memerlukan oksigen'], 0,
        'Tarikan nafas ialah proses pembekalan, manakala pembebasan tenaga berlaku dalam sel.'),
      m('Kenapa seseorang yang mengalami dehidrasi teruk boleh pengsan?', ['Isi padu darah berkurang dan bekalan oksigen ke otak terjejas', 'Otak menjadi terlalu sejuk', 'Peparu berhenti', 'Ginjal membesar'], 0,
        'Tekanan darah yang jatuh mengurangkan aliran darah ke otak.'),
      m('Apakah sebab utama penyakit paru-paru kronik sukar dirawat sepenuhnya?', ['Tisu peparu yang rosak tidak dapat tumbuh semula seperti asal', 'Ubat terlalu mahal', 'Peparu terlalu besar', 'Pesakit tidak berminat'], 0,
        'Rawatan boleh melambatkan penyakit tetapi tidak mengembalikan tisu yang musnah.'),
      m('Kenapa peluh yang tidak dapat tersejat menyebabkan badan terasa lebih panas?', ['Penyejukan hanya berlaku semasa air bertukar menjadi wap', 'Peluh memanaskan kulit', 'Peluh menutup liang', 'Peluh menambah haba'], 0,
        'Dalam udara yang sangat lembap, peluh menitis tanpa menyejukkan badan.'),
      m('Apakah bukti bahawa sistem perkumuhan dan sistem pernafasan saling berkait?', ['Peparu membuang karbon dioksida yang juga merupakan bahan kumuh', 'Kedua-duanya menggunakan ginjal', 'Kedua-duanya menghasilkan tenaga', 'Kedua-duanya menapis darah'], 0,
        'Pembuangan karbon dioksida ialah satu bentuk perkumuhan yang dilakukan oleh peparu.')
    ]
  },

  // ------------------------------------------------------------- 3. Haiwan
  {
    mudah: [
      m('Apakah maksud pembiakan?', ['Proses menghasilkan individu baharu daripada spesies yang sama', 'Proses membesar', 'Proses bernafas', 'Proses makan'], 0,
        'Pembiakan memastikan spesies tidak pupus.'),
      m('Haiwan manakah membiak dengan bertelur di dalam air?', ['Katak', 'Ayam', 'Kucing', 'Arnab'], 0,
        'Telur katak berlapis jeli dan mesti kekal dalam air.'),
      m('Apakah maksud kepupusan?', ['Kehilangan sesuatu spesies sepenuhnya dari bumi', 'Perpindahan haiwan', 'Tidur panjang haiwan', 'Perubahan warna haiwan'], 0,
        'Spesies yang pupus tidak akan kembali.'),
      m('Apakah cara haiwan melindungi anaknya?', ['Membina sarang dan menjaga anak', 'Meninggalkan anak sentiasa', 'Memakan anak', 'Tidak berbuat apa-apa'], 0,
        'Penjagaan induk meningkatkan peluang anak terus hidup.'),
      m('Haiwan manakah menjaga telurnya sehingga menetas?', ['Ayam', 'Ikan biasa', 'Kupu-kupu', 'Katak'], 0,
        'Ayam mengeram telurnya untuk mengekalkan suhu.'),
      m('Apakah maksud kitar hidup?', ['Peringkat pertumbuhan haiwan dari lahir hingga dewasa dan membiak', 'Tempat haiwan tinggal', 'Makanan haiwan', 'Bunyi haiwan'], 0,
        'Kitar hidup menerangkan urutan perubahan sepanjang hayat.'),
      m('Berapakah peringkat dalam kitar hidup kupu-kupu?', ['Empat', 'Dua', 'Tiga', 'Lima'], 0,
        'Telur, larva, pupa dan dewasa.'),
      m('Haiwan manakah mengalami kitar hidup tiga peringkat?', ['Lipas', 'Kupu-kupu', 'Nyamuk', 'Kumbang'], 0,
        'Lipas melalui telur, nimfa dan dewasa tanpa peringkat pupa.'),
      m('Apakah tujuan haiwan berhijrah?', ['Mencari makanan dan tempat membiak yang sesuai', 'Mencari kawan bermain', 'Mengelak cahaya', 'Menukar warna'], 0,
        'Penghijrahan mengikuti perubahan musim dan bekalan makanan.'),
      m('Kenapa haiwan liar dilindungi undang-undang?', ['Untuk mengelakkan kepupusan akibat pemburuan', 'Untuk menjadikannya mahal', 'Untuk mengurangkan bilangannya', 'Untuk memudahkan pemburuan'], 0,
        'Perlindungan undang-undang menghadkan pemburuan dan perdagangan.')
    ],
    sederhana: [
      m('Kenapa penyu bertelur dalam jumlah yang sangat banyak?', ['Kebanyakan anak penyu tidak sempat menjadi dewasa', 'Telurnya sangat kecil', 'Ia mahu mengisi pantai', 'Telur mudah dibuat'], 0,
        'Kadar kemandirian yang rendah memerlukan bilangan yang tinggi.'),
      m('Apakah perbezaan antara nimfa dan larva?', ['Nimfa menyerupai dewasa manakala larva sangat berbeza', 'Nimfa lebih besar', 'Larva tidak makan', 'Nimfa hidup dalam air sahaja'], 0,
        'Kitar hidup tiga peringkat menghasilkan anak yang menyerupai dewasa.'),
      m('Kenapa nyamuk perlu air bertakung untuk membiak?', ['Peringkat larva dan pupanya hidup dalam air', 'Nyamuk dewasa hidup dalam air', 'Telur perlu kering', 'Air memberi makanan dewasa'], 0,
        'Menghapuskan air bertakung memutuskan kitar hidupnya.'),
      m('Apakah kelebihan haiwan yang menjaga anak dalam kumpulan?', ['Anak lebih terlindung daripada pemangsa', 'Anak makan lebih sedikit', 'Anak membesar lebih perlahan', 'Anak tidak perlu belajar'], 0,
        'Kumpulan memberikan lebih banyak mata untuk mengawasi bahaya.'),
      m('Kenapa haiwan yang hidup di kawasan sejuk berbulu tebal?', ['Bulu memerangkap udara yang menebat haba badan', 'Bulu menghasilkan haba', 'Bulu menyerap cahaya sahaja', 'Bulu menambah berat'], 0,
        'Udara terperangkap ialah penebat yang sangat baik.'),
      m('Apakah kesan pemburuan haram terhadap populasi haiwan?', ['Bilangan menurun sehingga spesies terancam pupus', 'Bilangan bertambah', 'Tiada kesan', 'Haiwan menjadi lebih kuat'], 0,
        'Pengurangan yang lebih cepat daripada kadar pembiakan membawa kepada kepupusan.'),
      m('Kenapa habitat yang musnah menyukarkan pembiakan haiwan?', ['Tempat bersarang, makanan dan pasangan menjadi sukar diperoleh', 'Haiwan menjadi malas', 'Haiwan bertukar spesies', 'Haiwan berhenti makan'], 0,
        'Pembiakan memerlukan keadaan persekitaran yang sesuai.'),
      m('Apakah maksud spesies terancam?', ['Bilangannya sangat rendah dan berisiko pupus', 'Bilangannya bertambah pesat', 'Ia berbahaya kepada manusia', 'Ia hidup di hutan sahaja'], 0,
        'Status terancam menandakan keperluan perlindungan segera.'),
      m('Kenapa zoo dan pusat pemuliharaan membiakkan haiwan terancam?', ['Untuk menambah bilangan dan melepaskan semula ke habitat', 'Untuk menjual haiwan', 'Untuk hiburan sahaja', 'Untuk mengurangkan bilangan'], 0,
        'Program pembiakan menjadi jaringan keselamatan bagi spesies yang hampir pupus.'),
      m('Apakah kelebihan haiwan yang boleh membiak dengan cepat?', ['Populasi pulih lebih cepat selepas kehilangan besar', 'Setiap anak lebih kuat', 'Anak hidup lebih lama', 'Anak tidak perlu makan'], 0,
        'Kadar pembiakan tinggi membantu spesies bertahan daripada tekanan mendadak.')
    ],
    cabaran: [
      m('Kenapa spesies dengan kadar pembiakan rendah lebih mudah pupus?', ['Populasi mengambil masa sangat lama untuk pulih selepas kehilangan', 'Anaknya lemah', 'Ia tidak boleh berhijrah', 'Ia tidak mempunyai pemangsa'], 0,
        'Gajah dan badak yang melahirkan satu anak dalam beberapa tahun sangat terdedah.'),
      m('Apakah kesan menghapuskan pemangsa sepenuhnya daripada satu habitat?', ['Populasi mangsa meningkat melampau dan merosakkan tumbuhan', 'Semua haiwan mati', 'Tiada kesan', 'Mangsa berhenti membiak'], 0,
        'Pemangsa mengawal keseimbangan populasi dalam ekosistem.'),
      m('Kenapa program pelepasan semula haiwan ke hutan sering gagal?', ['Haiwan yang dibela kurang kemahiran mencari makan dan mengelak bahaya', 'Hutan terlalu besar', 'Haiwan tidak suka hutan', 'Makanan terlalu banyak'], 0,
        'Kemahiran hidup liar dipelajari dan bukan semata-mata semula jadi.'),
      m('Apakah kelemahan bergantung pada satu habitat sahaja bagi sesuatu spesies?', ['Kemusnahan habitat itu boleh memupuskan spesies tersebut', 'Spesies menjadi lebih kuat', 'Spesies membiak lebih cepat', 'Tiada kelemahan'], 0,
        'Spesies yang tersebar luas lebih mampu bertahan daripada bencana tempatan.'),
      m('Kenapa nyamuk Aedes sukar dihapuskan sepenuhnya?', ['Ia boleh membiak dalam takungan air yang sangat kecil di banyak tempat', 'Ia terlalu besar', 'Ia hidup dalam tanah', 'Ia tidak bertelur'], 0,
        'Bilangan tempat pembiakan yang banyak menjadikan kawalan sukar.'),
      m('Apakah kesan perubahan iklim terhadap haiwan yang berhijrah mengikut musim?', ['Masa penghijrahan tidak lagi sepadan dengan bekalan makanan', 'Haiwan berhenti berhijrah dengan mudah', 'Makanan bertambah', 'Tiada kesan'], 0,
        'Ketidaksepadanan masa boleh menyebabkan anak kelaparan.'),
      m('Kenapa kepelbagaian spesies penting dalam sesebuah ekosistem?', ['Sistem yang pelbagai lebih tahan terhadap penyakit dan gangguan', 'Ia kelihatan lebih menarik', 'Ia mengurangkan makanan', 'Ia memudahkan pemburuan'], 0,
        'Jika satu spesies gagal, spesies lain boleh mengambil peranannya.'),
      m('Apakah maksud haiwan endemik dan mengapa ia berisiko tinggi?', ['Ia hanya wujud di satu kawasan, jadi kemusnahan kawasan itu memupuskannya', 'Ia hidup di seluruh dunia', 'Ia sangat banyak', 'Ia tidak membiak'], 0,
        'Taburan yang sempit bermakna tiada populasi cadangan di tempat lain.'),
      m('Kenapa perdagangan haiwan eksotik memberi kesan berganda?', ['Ia mengurangkan populasi liar dan boleh membawa spesies asing ke habitat baharu', 'Ia hanya menjejaskan harga', 'Ia meningkatkan populasi liar', 'Ia tidak memberi kesan'], 0,
        'Haiwan yang terlepas boleh menjadi spesies invasif yang mengganggu ekosistem tempatan.'),
      m('Apakah bukti terbaik bahawa satu program pemuliharaan berjaya?', ['Populasi liar meningkat dan membiak sendiri tanpa bantuan', 'Bilangan di zoo bertambah', 'Lebih banyak wang dibelanjakan', 'Lebih ramai pelawat datang'], 0,
        'Kejayaan sebenar ialah populasi yang mampan di habitat asalnya.')
    ],
    ultra: [
      m('Kenapa populasi kecil menghadapi masalah walaupun dilindungi sepenuhnya?', ['Kepelbagaian genetik yang rendah melemahkan daya tahan spesies', 'Ia tidak dapat makanan', 'Ia terlalu besar', 'Ia tidak boleh bergerak'], 0,
        'Pembiakan dalam kumpulan yang terlalu kecil meningkatkan risiko penyakit dan kecacatan.'),
      m('Apakah kesan pembinaan jalan raya yang membelah hutan kepada populasi haiwan?', ['Populasi terpisah menjadi kumpulan kecil yang terasing', 'Haiwan mendapat lebih banyak ruang', 'Populasi bertambah', 'Tiada kesan'], 0,
        'Pemecahan habitat menghalang pertukaran genetik antara kumpulan.'),
      m('Kenapa koridor hidupan liar dibina merentasi lebuh raya?', ['Untuk membolehkan haiwan bergerak antara kawasan hutan yang terpisah', 'Untuk memudahkan pemburuan', 'Untuk menghiasi lebuh raya', 'Untuk mengurangkan pokok'], 0,
        'Sambungan semula habitat mengembalikan aliran genetik dan laluan mencari makan.'),
      m('Apakah hubungan antara kehilangan pendebunga dan populasi haiwan pemakan buah?', ['Kurang buah bermakna kurang makanan untuk haiwan tersebut', 'Tiada hubungan', 'Haiwan menjadi pemangsa', 'Buah bertambah'], 0,
        'Kesan bermula pada tumbuhan dan merebak ke seluruh rantai makanan.'),
      m('Kenapa spesies invasif boleh memusnahkan ekosistem tempatan dengan cepat?', ['Ia tiada pemangsa semula jadi di kawasan baharu', 'Ia sangat lemah', 'Ia tidak membiak', 'Ia memakan tanah'], 0,
        'Tanpa kawalan semula jadi, populasinya meningkat tanpa had.'),
      m('Apakah kelemahan mengukur kejayaan pemuliharaan hanya dengan bilangan individu?', ['Ia mengabaikan kesihatan genetik dan keadaan habitat', 'Bilangan tidak boleh dikira', 'Bilangan sentiasa salah', 'Bilangan tidak penting langsung'], 0,
        'Populasi yang ramai tetapi lemah dari segi genetik masih terdedah kepada kepupusan.'),
      m('Kenapa kepupusan satu spesies boleh mencetuskan kepupusan spesies lain?', ['Spesies yang bergantung padanya untuk makanan atau tempat tinggal turut terjejas', 'Semua spesies mati serentak', 'Tiada kaitan antara spesies', 'Spesies lain menjadi lebih kuat'], 0,
        'Hubungan dalam ekosistem menjadikan kehilangan satu spesies satu kesan berantai.'),
      m('Apakah cabaran utama membiakkan haiwan terancam dalam kurungan?', ['Tingkah laku mengawan semula jadi sukar berlaku dalam persekitaran buatan', 'Haiwan terlalu banyak', 'Makanan terlalu murah', 'Kurungan terlalu besar'], 0,
        'Banyak spesies memerlukan isyarat persekitaran tertentu untuk membiak.'),
      m('Kenapa perlindungan habitat lebih berkesan daripada melindungi satu spesies sahaja?', ['Ia melindungi seluruh rangkaian hidupan yang saling bergantung', 'Ia lebih murah sahaja', 'Ia lebih mudah dikawal', 'Spesies tunggal tidak penting'], 0,
        'Habitat yang sihat menyokong ratusan spesies serentak.'),
      m('Apakah maksud kadar kepupusan semasa jauh lebih tinggi daripada kadar semula jadi?', ['Aktiviti manusia mempercepatkan kehilangan spesies berbanding sejarah bumi', 'Bumi menjadi lebih tua', 'Spesies membiak lebih perlahan sendiri', 'Kadar itu sentiasa sama'], 0,
        'Perbandingan dengan rekod fosil menunjukkan peningkatan yang sangat ketara.')
    ]
  },

  // ----------------------------------------------------------- 4. Tumbuhan
  {
    mudah: [
      m('Apakah maksud pembiakan tumbuhan secara vegetatif?', ['Tumbuhan baharu terhasil daripada bahagian tumbuhan induk', 'Tumbuhan baharu terhasil daripada biji', 'Tumbuhan berpindah tempat', 'Tumbuhan bertukar warna'], 0,
        'Pembiakan vegetatif tidak melibatkan biji atau bunga.'),
      m('Tumbuhan manakah membiak melalui keratan batang?', ['Bunga raya', 'Padi', 'Jagung', 'Kacang'], 0,
        'Keratan batang bunga raya boleh tumbuh menjadi pokok baharu.'),
      m('Tumbuhan manakah membiak melalui ubi?', ['Keladi', 'Padi', 'Durian', 'Kelapa'], 0,
        'Ubi menyimpan makanan dan menghasilkan pucuk baharu.'),
      m('Tumbuhan manakah membiak melalui sulur?', ['Strawberi', 'Padi', 'Jagung', 'Rambutan'], 0,
        'Sulur menjalar dan menghasilkan akar serta pucuk baharu.'),
      m('Tumbuhan manakah membiak melalui spora?', ['Paku pakis', 'Durian', 'Padi', 'Kelapa'], 0,
        'Paku pakis menghasilkan spora di bawah daunnya.'),
      m('Tumbuhan manakah membiak melalui daun?', ['Setawar', 'Padi', 'Jagung', 'Kelapa'], 0,
        'Tumbuhan setawar menghasilkan anak pokok pada tepi daunnya.'),
      m('Apakah bahagian bunga yang menghasilkan debunga?', ['Stamen', 'Stigma', 'Ovari', 'Kelopak'], 0,
        'Stamen ialah bahagian jantan bunga.'),
      m('Apakah bahagian bunga yang menerima debunga?', ['Stigma', 'Stamen', 'Kelopak', 'Tangkai'], 0,
        'Stigma ialah bahagian atas struktur betina bunga.'),
      m('Apakah yang berlaku selepas persenyawaan dalam bunga?', ['Ovul menjadi biji dan ovari menjadi buah', 'Bunga menjadi daun', 'Akar menjadi batang', 'Batang menjadi bunga'], 0,
        'Buah melindungi biji yang sedang terbentuk.'),
      m('Kenapa petani menggunakan keratan batang untuk menanam pokok?', ['Anak pokok cepat tumbuh dan sama ciri dengan induk', 'Ia lebih mahal', 'Ia lebih perlahan', 'Ia menghasilkan biji'], 0,
        'Pembiakan vegetatif menghasilkan pokok yang serupa dengan induknya.')
    ],
    sederhana: [
      m('Apakah kelebihan pembiakan vegetatif berbanding biji?', ['Anak pokok mengekalkan ciri baik induk dan cepat berbuah', 'Anak pokok lebih pelbagai', 'Anak pokok lebih kecil', 'Anak pokok tidak perlu air'], 0,
        'Petani boleh mengekalkan kualiti pokok induk yang terbukti baik.'),
      m('Apakah kelemahan utama pembiakan vegetatif?', ['Semua pokok serupa, jadi satu penyakit boleh memusnahkan kesemuanya', 'Pokok terlalu kuat', 'Pokok tidak berbuah', 'Pokok terlalu tinggi'], 0,
        'Kekurangan kepelbagaian genetik menjadikan seluruh ladang terdedah.'),
      m('Kenapa pendebungaan silang menghasilkan tumbuhan yang lebih pelbagai?', ['Ciri daripada dua pokok berbeza bergabung', 'Debunga menjadi lebih besar', 'Bunga menjadi lebih banyak', 'Biji menjadi lebih kecil'], 0,
        'Gabungan baharu menghasilkan kombinasi ciri yang tidak ada pada induk.'),
      m('Apakah agen pendebungaan bagi bunga yang kecil, tidak berwarna dan tidak berbau?', ['Angin', 'Lebah', 'Rama-rama', 'Burung'], 0,
        'Bunga yang didebungakan angin tidak perlu menarik haiwan.'),
      m('Kenapa bunga yang didebungakan angin menghasilkan debunga yang sangat banyak?', ['Kebanyakan debunga tidak sampai ke stigma bunga lain', 'Debunga terlalu berat', 'Angin tidak bertiup', 'Debunga mudah dibuat'], 0,
        'Penyebaran secara rawak memerlukan kuantiti yang besar.'),
      m('Apakah tujuan biji mempunyai kulit yang keras?', ['Melindungi embrio sehingga keadaan sesuai untuk bercambah', 'Menambah berat', 'Menarik haiwan', 'Menyerap cahaya'], 0,
        'Kulit biji melindungi embrio daripada kekeringan dan kerosakan.'),
      m('Apakah keadaan yang diperlukan biji untuk bercambah?', ['Air, udara dan suhu yang sesuai', 'Cahaya matahari yang kuat sahaja', 'Tanah yang kering', 'Bunyi dan angin'], 0,
        'Kebanyakan biji tidak memerlukan cahaya untuk mula bercambah.'),
      m('Kenapa biji tidak bercambah dalam bekas yang tertutup rapat tanpa udara?', ['Embrio memerlukan oksigen untuk membebaskan tenaga', 'Biji memerlukan bunyi', 'Biji memerlukan cahaya', 'Biji terlalu sejuk'], 0,
        'Pernafasan sel dalam biji memerlukan oksigen.'),
      m('Apakah kelebihan pencantuman pokok buah?', ['Menggabungkan akar yang kuat dengan buah yang berkualiti', 'Menjadikan pokok lebih tinggi', 'Menghasilkan biji lebih besar', 'Menjadikan pokok lebih murah'], 0,
        'Dua bahagian daripada pokok berbeza digabungkan untuk mendapat kelebihan kedua-duanya.'),
      m('Kenapa petani menyemai biji dengan jarak tertentu?', ['Supaya setiap pokok mendapat cahaya, air dan mineral yang mencukupi', 'Supaya ladang kelihatan kemas', 'Supaya lebih mudah dituai', 'Supaya biji lebih murah'], 0,
        'Persaingan sumber mengurangkan hasil setiap pokok.')
    ],
    cabaran: [
      m('Kenapa satu ladang pisang yang semuanya daripada satu klon berisiko tinggi?', ['Penyakit yang menyerang satu pokok boleh memusnahkan seluruh ladang', 'Pokok tumbuh terlalu cepat', 'Buah terlalu besar', 'Pokok tidak berbuah'], 0,
        'Ketiadaan kepelbagaian genetik bermakna tiada pokok yang tahan penyakit itu.'),
      m('Apakah kesan menggunakan racun rumpai berlebihan terhadap tanaman?', ['Baki racun boleh merosakkan tanaman dan mencemarkan tanah', 'Tanaman menjadi lebih besar', 'Tanah menjadi lebih subur', 'Tiada kesan'], 0,
        'Bahan kimia yang terkumpul memberi kesan melangkaui sasaran asalnya.'),
      m('Kenapa biji sesetengah tumbuhan hanya bercambah selepas kebakaran hutan?', ['Haba memecahkan kulit biji dan abu menyuburkan tanah', 'Biji suka api', 'Api menghasilkan air', 'Biji memerlukan asap sahaja'], 0,
        'Sesetengah spesies menyesuaikan diri dengan kitaran kebakaran semula jadi.'),
      m('Apakah kesan menanam satu jenis tanaman sahaja secara berterusan di tanah yang sama?', ['Mineral tertentu habis dan perosak khusus meningkat', 'Tanah menjadi lebih subur', 'Hasil bertambah setiap tahun', 'Tiada kesan'], 0,
        'Penggiliran tanaman digunakan untuk mengatasi masalah ini.'),
      m('Kenapa rumah hijau membolehkan tumbuhan tumbuh di luar musim?', ['Suhu, cahaya dan kelembapan boleh dikawal', 'Tumbuhan menjadi lebih kuat sendiri', 'Biji berubah', 'Tanah menjadi berbeza'], 0,
        'Persekitaran terkawal menghapuskan halangan musim.'),
      m('Apakah kelebihan menanam tumbuhan penutup bumi di ladang?', ['Ia mengurangkan hakisan dan menahan kelembapan tanah', 'Ia menambah perosak', 'Ia mengurangkan hasil', 'Ia menyerap semua mineral'], 0,
        'Penutup tanah melindungi lapisan atas daripada hujan dan matahari terik.'),
      m('Kenapa biji yang terlalu dalam ditanam gagal tumbuh?', ['Simpanan makanan dalam biji habis sebelum pucuk mencapai cahaya', 'Tanah terlalu sejuk', 'Biji terlalu kecil', 'Air terlalu banyak'], 0,
        'Biji hanya mempunyai tenaga terhad sebelum ia boleh berfotosintesis.'),
      m('Apakah kesan jangka panjang menggunakan baja kimia sahaja tanpa bahan organik?', ['Struktur tanah merosot dan keupayaannya menyimpan air berkurang', 'Tanah menjadi lebih gembur', 'Hasil meningkat selamanya', 'Tiada kesan'], 0,
        'Bahan organik memberi struktur dan kehidupan mikrob kepada tanah.'),
      m('Kenapa sesetengah tumbuhan menghasilkan bunga jantan dan betina pada pokok berasingan?', ['Ia memastikan pendebungaan silang berlaku', 'Ia menjimatkan tenaga', 'Ia menghasilkan lebih banyak biji', 'Ia mengurangkan bunga'], 0,
        'Pemisahan menghalang pendebungaan sendiri sepenuhnya.'),
      m('Apakah bukti bahawa penyebaran biji berkesan bagi sesuatu spesies?', ['Anak pokok ditemui jauh daripada pokok induk', 'Biji sangat besar', 'Bunga sangat cantik', 'Pokok sangat tinggi'], 0,
        'Taburan anak pokok menunjukkan jarak penyebaran yang sebenar berlaku.')
    ],
    ultra: [
      m('Kenapa kepelbagaian genetik dalam tanaman penting untuk keselamatan makanan?', ['Ia membolehkan sesetengah varieti bertahan apabila penyakit atau iklim berubah', 'Ia menjadikan buah lebih besar', 'Ia mengurangkan kos', 'Ia mempercepatkan tuaian'], 0,
        'Kepelbagaian ialah insurans terhadap ancaman yang belum diketahui.'),
      m('Apakah kaitan antara bank biji dunia dan pemuliharaan tanaman?', ['Ia menyimpan varieti biji untuk masa depan jika varieti semasa gagal', 'Ia menjual biji', 'Ia menanam semua biji', 'Ia memusnahkan biji lama'], 0,
        'Simpanan biji menjadi cadangan genetik bagi seluruh dunia.'),
      m('Kenapa pendebungaan sendiri berterusan melemahkan sesuatu spesies tumbuhan?', ['Kepelbagaian genetik berkurang dan ciri lemah lebih kerap muncul', 'Bunga menjadi kecil', 'Biji menjadi terlalu besar', 'Pokok tumbuh terlalu tinggi'], 0,
        'Gabungan gen yang sama berulang meningkatkan kemunculan ciri yang merugikan.'),
      m('Apakah kesan kehilangan pendebunga terhadap keselamatan makanan dunia?', ['Hasil banyak tanaman buah dan sayur menurun dengan ketara', 'Hanya bunga hiasan terjejas', 'Padi terjejas paling teruk', 'Tiada kesan'], 0,
        'Sebahagian besar tanaman makanan bergantung pada pendebungaan haiwan.'),
      m('Kenapa tumbuhan yang tumbuh dalam tanah masin sukar menyerap air?', ['Kepekatan garam di luar akar menghalang air memasuki akar', 'Garam menutup akar', 'Air menjadi terlalu berat', 'Akar menjadi keras'], 0,
        'Air bergerak ke arah kepekatan larutan yang lebih tinggi.'),
      m('Apakah kelebihan sistem tanaman bercampur berbanding satu jenis sahaja?', ['Perosak kurang merebak dan tanah kekal lebih seimbang', 'Hasil sentiasa lebih tinggi', 'Kos lebih rendah sentiasa', 'Tuaian lebih mudah'], 0,
        'Kepelbagaian dalam ladang meniru kestabilan sistem semula jadi.'),
      m('Kenapa penggunaan varieti tahan penyakit bukan penyelesaian kekal?', ['Penyakit berubah dan akhirnya boleh mengatasi ketahanan itu', 'Varieti itu tidak berbuah', 'Varieti itu terlalu mahal', 'Penyakit hilang sendiri'], 0,
        'Perlumbaan antara tanaman dan penyakit berterusan sepanjang masa.'),
      m('Apakah hubungan antara kesuburan tanah dan organisma kecil di dalamnya?', ['Mikrob dan cacing menguraikan bahan organik menjadi mineral yang boleh diserap', 'Organisma memakan akar sahaja', 'Organisma tidak berkaitan', 'Organisma mengeraskan tanah'], 0,
        'Tanah yang hidup ialah sistem biologi, bukan sekadar bahan tidak hidup.'),
      m('Kenapa hasil tanaman menurun walaupun baja ditambah selepas beberapa tahun?', ['Faktor lain seperti struktur tanah dan air menjadi penghad', 'Baja menjadi tidak berguna', 'Tanaman berhenti tumbuh', 'Biji menjadi lemah'], 0,
        'Pertumbuhan dihadkan oleh faktor yang paling kurang, bukan yang paling banyak.'),
      m('Apakah kelebihan menyimpan biji tempatan berbanding membeli biji komersial setiap musim?', ['Biji tempatan sudah sesuai dengan iklim dan tanah kawasan itu', 'Biji tempatan lebih besar', 'Biji tempatan lebih cantik', 'Biji tempatan tidak perlu air'], 0,
        'Penyesuaian tempatan terbentuk melalui banyak musim penanaman.')
    ]
  }
];
