// Soalan Sains Darjah 1, sepuluh bab.
//
// Bahasa dijaga supaya budak tujuh tahun boleh membacanya sendiri. Ayat
// pendek, tiada istilah yang belum diajar, dan langkah kerja menerangkan
// sebabnya dan bukan sekadar mengulang jawapan.

import { m, i } from './soalan.mjs';

export default [
  // ------------------------------------------------ 1. Kemahiran Saintifik
  {
    mudah: [
      m('Berapa banyak deria yang ada pada manusia?', ['5', '3', '4', '6'], 0,
        'Manusia ada lima deria: penglihatan, pendengaran, bau, rasa dan sentuh.'),
      m('Kita menggunakan deria apa untuk melihat warna?', ['Penglihatan', 'Pendengaran', 'Bau', 'Rasa'], 0,
        'Mata memberi kita deria penglihatan, dan warna dilihat dengan mata.'),
      m('Alat manakah digunakan untuk mengukur panjang?', ['Pembaris', 'Jam', 'Neraca', 'Termometer'], 0,
        'Pembaris mengukur panjang. Jam mengukur masa dan neraca mengukur berat.'),
      m('Kita menggunakan deria apa untuk mendengar bunyi loceng?', ['Pendengaran', 'Penglihatan', 'Sentuh', 'Bau'], 0,
        'Telinga memberi kita deria pendengaran.'),
      m('Deria apa yang kita guna untuk tahu bau nasi goreng?', ['Bau', 'Rasa', 'Sentuh', 'Penglihatan'], 0,
        'Hidung memberi kita deria bau.'),
      m('Alat manakah digunakan untuk mengukur masa?', ['Jam', 'Pembaris', 'Neraca', 'Cawan penyukat'], 0,
        'Jam mengukur masa.'),
      m('Kita tahu air itu panas atau sejuk dengan deria apa?', ['Sentuh', 'Bau', 'Pendengaran', 'Penglihatan'], 0,
        'Kulit memberi kita deria sentuh, dan kulit merasa panas atau sejuk.'),
      m('Apakah yang kita buat apabila kita "memerhati"?', ['Menggunakan deria untuk mendapat maklumat', 'Meneka sahaja', 'Menulis nama', 'Berlari pantas'], 0,
        'Memerhati bermakna menggunakan deria kita untuk mengumpul maklumat tentang sesuatu.'),
      m('Alat manakah digunakan untuk mengukur isi padu air?', ['Silinder penyukat', 'Pembaris', 'Jam', 'Termometer'], 0,
        'Silinder penyukat mengukur berapa banyak air, iaitu isi padunya.'),
      m('Deria rasa datang daripada bahagian badan yang mana?', ['Lidah', 'Hidung', 'Telinga', 'Mata'], 0,
        'Lidah memberi kita deria rasa.')
    ],
    sederhana: [
      m('Ali menutup matanya dan memegang sebiji buah. Deria manakah yang dia guna?', ['Sentuh', 'Penglihatan', 'Pendengaran', 'Bau'], 0,
        'Matanya tertutup, jadi dia tidak boleh melihat. Dia menggunakan kulit tangannya, iaitu deria sentuh.'),
      m('Rina hendak tahu buku mana lebih panjang. Apakah yang patut dia guna?', ['Pembaris', 'Jam', 'Termometer', 'Neraca'], 0,
        'Panjang diukur dengan pembaris.'),
      m('Siti mengumpulkan butang mengikut warna. Kemahiran apakah itu?', ['Mengelas', 'Mengukur', 'Meramal', 'Berkomunikasi'], 0,
        'Mengumpulkan benda mengikut ciri yang sama dipanggil mengelas.'),
      m('Manakah antara berikut TIDAK boleh diketahui hanya dengan melihat?', ['Rasa manis gula', 'Warna bola', 'Bentuk kotak', 'Saiz buku'], 0,
        'Rasa hanya boleh diketahui dengan lidah. Warna, bentuk dan saiz boleh dilihat dengan mata.'),
      m('Ali kata "esok akan hujan kerana langit gelap." Kemahiran apakah itu?', ['Meramal', 'Mengukur', 'Mengelas', 'Memerhati'], 0,
        'Mengatakan apa yang akan berlaku nanti dipanggil meramal.'),
      i('Berapakah bilangan deria yang digunakan apabila kita makan buah sambil memandangnya?', 3,
        'Kita melihat buah itu, menghidu baunya dan merasa rasanya. Itu tiga deria. (Sentuhan pada lidah juga ada, tetapi tiga sudah cukup untuk soalan ini.)'),
      m('Untuk mengukur berat sebiji tembikai, apakah alat yang sesuai?', ['Neraca', 'Pembaris', 'Jam', 'Silinder penyukat'], 0,
        'Berat diukur dengan neraca.'),
      m('Manakah pasangan yang betul?', ['Telinga dan pendengaran', 'Telinga dan bau', 'Hidung dan rasa', 'Mata dan sentuh'], 0,
        'Telinga memberi deria pendengaran. Hidung memberi bau, lidah memberi rasa, mata memberi penglihatan.'),
      m('Rina menyusun daun daripada kecil ke besar. Apakah yang dia ukur?', ['Saiz', 'Bau', 'Bunyi', 'Rasa'], 0,
        'Menyusun mengikut kecil dan besar bermakna dia membandingkan saiz.'),
      m('Kenapa kita tidak boleh merasa bahan yang tidak dikenali di dalam bilik sains?', ['Ia mungkin berbahaya', 'Ia sejuk', 'Ia berat', 'Ia mahal'], 0,
        'Bahan yang tidak dikenali mungkin racun atau berbahaya, jadi kita tidak boleh merasanya.')
    ],
    cabaran: [
      m('Ali memegang dua bekas tertutup. Satu berbunyi bila digoncang, satu senyap. Deria apakah yang membantu dia membezakannya?', ['Pendengaran', 'Penglihatan', 'Bau', 'Rasa'], 0,
        'Bekas itu tertutup, jadi dia tidak nampak isinya. Bunyi goncangan didengar dengan telinga, iaitu deria pendengaran.'),
      i('Sebatang pensel panjangnya 12 cm dan sebatang lagi 8 cm. Berapakah beza panjang kedua-duanya, dalam cm?', 4,
        'Beza panjang = 12 − 8 = 4 cm.'),
      m('Siti mengasingkan bola kepada dua kumpulan: bulat dan tidak bulat. Apakah ciri yang dia guna untuk mengelas?', ['Bentuk', 'Warna', 'Berat', 'Bau'], 0,
        'Bulat dan tidak bulat ialah tentang rupa benda itu, iaitu bentuknya.'),
      m('Rina nampak awan hitam tebal di langit. Ramalan manakah paling munasabah?', ['Hujan akan turun', 'Matahari akan terbit', 'Angin akan berhenti', 'Bulan akan muncul'], 0,
        'Awan hitam tebal biasanya membawa hujan, jadi itu ramalan yang paling masuk akal.'),
      m('Ali ingin tahu air dalam mana antara dua cawan lebih banyak. Apakah cara yang paling tepat?', ['Tuang ke dalam silinder penyukat', 'Bau kedua-duanya', 'Dengar bunyinya', 'Sentuh cawan itu'], 0,
        'Isi padu air diukur dengan silinder penyukat. Bau, bunyi dan sentuhan tidak memberitahu berapa banyak air.'),
      i('Ada 5 deria pada manusia. Jika Ali menutup mata dan menutup telinga, berapa deria yang masih boleh dia guna?', 3,
        '5 deria tolak 2 yang ditutup = 3 deria yang tinggal, iaitu bau, rasa dan sentuh.'),
      m('Manakah antara berikut BUKAN kemahiran memerhati?', ['Meneka jawapan tanpa melihat', 'Melihat warna bunga', 'Mendengar bunyi burung', 'Menghidu bau roti'], 0,
        'Memerhati mesti menggunakan deria. Meneka tanpa melihat tidak menggunakan deria langsung.'),
      m('Sebuah bekas berisi air panas. Kenapa kita tidak sentuh terus dengan tangan?', ['Boleh melecur', 'Air jadi kotor', 'Bekas jadi berat', 'Air jadi sejuk'], 0,
        'Air panas boleh melecurkan kulit, jadi kita gunakan termometer atau sarung tangan.'),
      m('Ali menyusun kejadian: telur, anak ayam, ayam dewasa. Kemahiran apakah itu?', ['Menyusun mengikut urutan', 'Mengukur', 'Menimbang', 'Menghidu'], 0,
        'Meletakkan sesuatu mengikut susunan yang betul dari awal ke akhir dipanggil menyusun mengikut urutan.'),
      m('Dua bekas kelihatan sama besar tetapi satu lebih berat. Apakah yang boleh kita simpulkan?', ['Isi dalamnya berbeza', 'Warnanya berbeza', 'Bunyinya berbeza', 'Baunya berbeza'], 0,
        'Saiz sama tetapi berat berbeza bermakna apa yang ada di dalamnya tidak sama.')
    ],
    ultra: [
      m('Ali diberi tiga bekas tertutup yang sama rupa. Dia hanya dibenarkan menggoncang dan menimbangnya. Deria manakah TIDAK berguna langsung di sini?', ['Rasa', 'Pendengaran', 'Sentuh', 'Penglihatan'], 0,
        'Bekas tertutup, jadi dia tidak boleh merasa isinya. Dia boleh mendengar goncangan, merasa beratnya dengan tangan, dan melihat bekas itu.'),
      i('Siti mengukur 3 batang pensel: 9 cm, 14 cm dan 11 cm. Berapakah beza antara yang paling panjang dan paling pendek, dalam cm?', 5,
        'Paling panjang 14 cm, paling pendek 9 cm. Beza = 14 − 9 = 5 cm.'),
      m('Rina kata "bola ini akan terapung" sebelum meletakkannya di dalam air. Selepas itu bola tenggelam. Apakah yang patut dia buat?', ['Terima pemerhatian dan betulkan ramalan', 'Katakan bola itu rosak', 'Buang bola itu', 'Ulang ramalan yang sama'], 0,
        'Dalam sains, pemerhatian sebenar lebih penting daripada ramalan. Ramalan yang salah dibetulkan, bukan dipaksa betul.'),
      m('Manakah cara terbaik untuk membandingkan berat dua benda yang hampir sama?', ['Guna neraca', 'Angkat dengan tangan', 'Lihat saiznya', 'Dengar bunyinya'], 0,
        'Tangan tidak boleh merasa beza kecil dengan tepat. Neraca memberi ukuran sebenar.'),
      m('Ali mengelas haiwan kepada "ada kaki" dan "tiada kaki". Manakah masuk kumpulan tiada kaki?', ['Ular', 'Kucing', 'Ayam', 'Katak'], 0,
        'Ular tidak berkaki. Kucing, ayam dan katak semuanya berkaki.'),
      i('Sebuah bekas mengandungi 250 ml air. Ditambah 150 ml lagi. Berapa ml air sekarang?', 400,
        '250 + 150 = 400 ml.'),
      m('Kenapa dua orang murid boleh mendapat ukuran berbeza bagi meja yang sama?', ['Mereka mula mengukur dari titik berbeza', 'Meja itu berubah saiz', 'Pembaris jadi panjang', 'Warna meja berubah'], 0,
        'Kalau pembaris tidak dimulakan dari hujung meja, ukurannya jadi salah. Meja itu sendiri tidak berubah.'),
      m('Ali hendak tahu adakah gula larut lebih cepat dalam air panas atau air sejuk. Apakah yang MESTI sama pada kedua-dua cawan?', ['Banyaknya gula', 'Suhu air', 'Warna cawan sahaja', 'Nama murid'], 0,
        'Hanya satu perkara boleh berbeza, iaitu suhu air. Banyaknya gula mesti sama, kalau tidak kita tidak tahu apa yang menyebabkan perbezaan.'),
      m('Deria manakah yang paling tidak selamat digunakan di dalam bilik sains?', ['Rasa', 'Penglihatan', 'Pendengaran', 'Sentuh'], 0,
        'Merasa bahan yang tidak dikenali boleh meracuni. Melihat dan mendengar tidak menyentuh bahan langsung.'),
      m('Siti memerhati bahawa tanah di bawah pokok sentiasa lembap. Inferens manakah paling munasabah?', ['Pokok itu melindungi tanah daripada matahari', 'Tanah itu berwarna gelap', 'Pokok itu tinggi', 'Tanah itu keras'], 0,
        'Daun pokok menghalang cahaya matahari, jadi air tidak cepat kering. Warna, ketinggian dan kekerasan tidak menjelaskan kelembapan.')
    ]
  },

  // ---------------------------------------------- 2. Peraturan Bilik Sains
  {
    mudah: [
      m('Sebelum menjalankan aktiviti sains, apakah yang mesti kita buat dahulu?', ['Dengar arahan guru', 'Bermain alat', 'Makan di dalam bilik', 'Berlari'], 0,
        'Arahan guru mesti didengar dahulu supaya aktiviti selamat.'),
      m('Bolehkah kita makan di dalam bilik sains?', ['Tidak boleh', 'Boleh', 'Boleh jika lapar', 'Boleh jika sedikit'], 0,
        'Bahan sains boleh melekat pada makanan dan meracuni kita, jadi makan tidak dibenarkan.'),
      m('Apakah yang perlu dipakai untuk melindungi mata?', ['Cermin mata keselamatan', 'Topi', 'Sarung kaki', 'Jam tangan'], 0,
        'Cermin mata keselamatan melindungi mata daripada percikan bahan.'),
      m('Jika sesuatu tumpah di atas lantai, apakah yang patut kita buat?', ['Beritahu guru', 'Biarkan sahaja', 'Pijak ia', 'Lari keluar'], 0,
        'Guru mesti diberitahu supaya ia dibersihkan dengan selamat sebelum ada orang tergelincir.'),
      m('Bolehkah kita berlari di dalam bilik sains?', ['Tidak boleh', 'Boleh', 'Boleh jika perlahan', 'Boleh jika seorang'], 0,
        'Berlari boleh menyebabkan kita melanggar meja dan memecahkan radas.'),
      m('Selepas menjalankan aktiviti, apakah yang mesti kita buat pada tangan?', ['Basuh dengan sabun', 'Lap pada baju', 'Biarkan sahaja', 'Tiup sahaja'], 0,
        'Membasuh tangan dengan sabun membuang bahan yang mungkin melekat.'),
      m('Alat kaca yang pecah patut dibuang ke mana?', ['Bekas khas untuk kaca pecah', 'Tong sampah biasa', 'Bawah meja', 'Poket'], 0,
        'Kaca pecah boleh melukakan orang, jadi ia dimasukkan ke dalam bekas khas.'),
      m('Bolehkah kita menghidu bahan kimia terus dari botolnya?', ['Tidak boleh', 'Boleh', 'Boleh jika sedikit', 'Boleh jika cepat'], 0,
        'Wasapnya boleh membahayakan hidung dan paru-paru.'),
      m('Rambut panjang patut diapakan semasa aktiviti sains?', ['Diikat', 'Dibiarkan', 'Ditutup dengan tangan', 'Dipotong'], 0,
        'Rambut panjang yang terurai boleh terkena api atau bahan.'),
      m('Siapakah yang patut kita beritahu jika kita cedera?', ['Guru', 'Kawan sahaja', 'Tiada siapa', 'Adik'], 0,
        'Guru tahu cara merawat dan memanggil bantuan.')
    ],
    sederhana: [
      m('Ali ternampak wayar berbulu terkeluar dari plug. Apakah yang patut dia buat?', ['Beritahu guru dan jangan sentuh', 'Tarik wayar itu', 'Tutup dengan kertas', 'Guna juga'], 0,
        'Wayar terdedah boleh menyebabkan renjatan elektrik. Jangan sentuh, beritahu guru.'),
      m('Kenapa kita perlu memakai apron semasa aktiviti sains?', ['Melindungi baju daripada bahan', 'Supaya nampak cantik', 'Supaya panas', 'Supaya senang berlari'], 0,
        'Apron menghalang bahan tumpah daripada terkena baju dan kulit.'),
      m('Rina mahu mengambil bekas panas. Apakah yang patut dia guna?', ['Penyepit atau kain tebal', 'Tangan kosong', 'Kertas nipis', 'Jari sahaja'], 0,
        'Bekas panas melecurkan kulit. Penyepit atau kain tebal menghalang haba.'),
      m('Manakah tindakan yang PALING selamat?', ['Membaca label sebelum menggunakan bahan', 'Mencampur bahan tanpa arahan', 'Merasa bahan', 'Menuang tanpa melihat'], 0,
        'Label memberitahu bahan itu apa dan bahayanya. Semua pilihan lain menggunakan bahan tanpa tahu apa-apa.'),
      m('Kenapa meja perlu dibersihkan selepas aktiviti?', ['Supaya orang seterusnya selamat', 'Supaya meja berkilat', 'Supaya cepat balik', 'Supaya guru gembira sahaja'], 0,
        'Sisa bahan yang tinggal boleh membahayakan kelas seterusnya.'),
      m('Ali terkena bahan kimia pada tangannya. Apakah langkah pertama?', ['Basuh dengan banyak air', 'Lap dengan baju', 'Tiup tangan', 'Biarkan kering'], 0,
        'Air yang banyak melarutkan dan membuang bahan itu dengan cepat.'),
      m('Kenapa kita tidak boleh bermain dengan radas sains?', ['Ia boleh pecah dan mencederakan', 'Ia berat', 'Ia mahal sahaja', 'Ia berwarna'], 0,
        'Kebanyakan radas diperbuat daripada kaca dan boleh pecah menjadi serpihan tajam.'),
      m('Manakah yang BUKAN peraturan bilik sains?', ['Berlari untuk mengambil radas', 'Ikut arahan guru', 'Basuh tangan selepas aktiviti', 'Pakai cermin mata keselamatan'], 0,
        'Berlari tidak pernah dibenarkan. Tiga yang lain semuanya peraturan yang betul.'),
      m('Kenapa botol bahan mesti ditutup semula selepas digunakan?', ['Supaya bahan tidak tumpah atau menyejat', 'Supaya botol cantik', 'Supaya botol berat', 'Supaya bahan sejuk'], 0,
        'Botol terbuka boleh tumpah, dan sesetengah bahan menyejat ke udara.'),
      m('Rina nampak kawannya cuba merasa serbuk putih. Apakah yang patut dia buat?', ['Halang dan beritahu guru', 'Turut merasa', 'Ketawa', 'Diam sahaja'], 0,
        'Serbuk yang tidak dikenali mungkin racun. Menghalang kawan dan memberitahu guru menyelamatkannya.')
    ],
    cabaran: [
      m('Api kecil terjadi di atas meja. Manakah tindakan pertama yang betul?', ['Beritahu guru dengan segera', 'Tiup api itu', 'Siram dengan sebarang cecair', 'Lari keluar tanpa memberitahu sesiapa'], 0,
        'Guru tahu alat pemadam yang betul. Meniup boleh merebakkan api, dan cecair yang salah boleh membuat api lebih besar.'),
      m('Kenapa arahan "jangan campur bahan tanpa kebenaran" penting?', ['Campuran boleh menghasilkan gas berbahaya', 'Campuran menjadi berat', 'Campuran menjadi sejuk', 'Campuran menjadi cantik'], 0,
        'Sesetengah bahan bertindak balas dan menghasilkan haba atau gas beracun apabila dicampur.'),
      m('Ali memakai apron tetapi tidak memakai cermin mata keselamatan semasa menuang cecair. Apakah risikonya?', ['Cecair boleh terpercik ke mata', 'Bajunya kotor', 'Tangannya sejuk', 'Cecair jadi panas'], 0,
        'Apron melindungi baju sahaja. Mata masih terdedah kepada percikan.'),
      m('Manakah susunan yang betul selepas aktiviti tamat?', ['Kemas radas, bersihkan meja, basuh tangan', 'Basuh tangan, keluar, tinggalkan radas', 'Keluar dahulu, kemas esok', 'Bersihkan meja sahaja'], 0,
        'Radas dikemas dahulu supaya meja boleh dibersihkan, dan tangan dibasuh terakhir kerana ia yang menyentuh segalanya.'),
      m('Kenapa kita tidak boleh berdiri terlalu dekat semasa memanaskan air?', ['Wap panas boleh melecur muka', 'Air jadi sejuk', 'Air jadi kotor', 'Bekas jadi berat'], 0,
        'Wap yang naik daripada air mendidih sangat panas dan boleh melecurkan kulit muka.'),
      m('Siti memecahkan bikar. Apakah tindakan yang BETUL?', ['Beritahu guru dan jangan kutip dengan tangan', 'Kutip serpihan dengan tangan', 'Sorok di bawah meja', 'Tolak ke tepi dengan kaki'], 0,
        'Serpihan kaca sangat tajam. Guru akan membersihkannya dengan alat yang betul.'),
      m('Kenapa beg sekolah patut diletakkan jauh dari laluan berjalan?', ['Supaya tiada orang tersandung', 'Supaya beg bersih', 'Supaya beg sejuk', 'Supaya senang dicari'], 0,
        'Beg di laluan menyebabkan orang tersandung, dan jatuh sambil memegang radas sangat berbahaya.'),
      m('Manakah yang menunjukkan murid memahami peraturan dengan BAIK?', ['Membaca label, memakai apron, dan bertanya guru bila ragu', 'Bekerja cepat tanpa bertanya', 'Mencuba bahan baharu sendiri', 'Menyimpan radas dalam beg'], 0,
        'Tiga tabiat itu semuanya mengurangkan risiko. Pilihan lain menambah risiko.'),
      m('Kenapa keputusan aktiviti perlu dicatat semasa aktiviti, bukan selepas balik?', ['Ingatan boleh salah', 'Kertas jadi lusuh', 'Pen habis dakwat', 'Guru marah'], 0,
        'Butiran mudah dilupakan. Catatan semasa itu lebih tepat daripada ingatan kemudian.'),
      m('Ali rasa pening selepas menghidu sesuatu. Apakah tindakan terbaik?', ['Keluar mencari udara segar dan beritahu guru', 'Duduk diam sahaja', 'Hidu lagi untuk pasti', 'Minum bahan itu'], 0,
        'Udara segar mengurangkan kesan wasap, dan guru perlu tahu untuk memberi bantuan.')
    ],
    ultra: [
      m('Sebuah kelas menjalankan aktiviti memanaskan air. Manakah gabungan langkah keselamatan yang PALING lengkap?', ['Cermin mata, rambut diikat, penyepit untuk bekas panas', 'Cermin mata sahaja', 'Rambut diikat sahaja', 'Apron dan makan tengah hari'], 0,
        'Air panas mengancam mata melalui percikan, rambut melalui api, dan tangan melalui bekas panas. Ketiga-tiganya perlu dilindungi.'),
      m('Kenapa peraturan "jangan bekerja seorang diri" wujud di dalam bilik sains?', ['Jika berlaku kemalangan, tiada siapa boleh memanggil bantuan', 'Kerja jadi lambat', 'Radas jadi kotor', 'Bilik jadi sunyi'], 0,
        'Dalam kemalangan, orang yang cedera mungkin tidak mampu memanggil bantuan sendiri.'),
      m('Dua murid tumpahkan bahan berbeza. Satu air, satu cecair berlabel bahaya. Manakah kenyataan yang BETUL?', ['Kedua-duanya dilaporkan, tetapi cecair berlabel bahaya perlu tindakan segera', 'Hanya air perlu dilaporkan', 'Kedua-duanya boleh diabaikan', 'Hanya yang berbau perlu dilaporkan'], 0,
        'Semua tumpahan dilaporkan kerana lantai licin membahayakan. Bahan berlabel bahaya menambah risiko kimia, jadi ia lebih mendesak.'),
      m('Seorang murid berkata peraturan sains melambatkan kerja. Jawapan terbaik ialah?', ['Peraturan menghalang kemalangan yang akan melambatkan lebih banyak', 'Peraturan memang membuang masa', 'Peraturan hanya untuk murid lemah', 'Peraturan boleh diabaikan jika berhati-hati'], 0,
        'Satu kemalangan menghentikan seluruh kelas dan boleh mencederakan orang. Beberapa saat untuk keselamatan menjimatkan masa yang jauh lebih banyak.'),
      m('Kenapa label bahan mengandungi simbol dan bukan perkataan sahaja?', ['Simbol difahami dengan cepat walaupun tanpa membaca', 'Simbol lebih cantik', 'Perkataan mahal dicetak', 'Simbol lebih kecil'], 0,
        'Dalam kecemasan tiada masa membaca ayat panjang. Simbol memberi amaran dalam sekelip mata.'),
      m('Manakah situasi yang paling berbahaya?', ['Berlari sambil membawa bikar kaca berisi cecair', 'Berjalan sambil membawa buku', 'Duduk membaca label', 'Berdiri memakai apron'], 0,
        'Berlari menggabungkan tiga risiko sekali gus: jatuh, kaca pecah dan cecair tumpah.'),
      m('Selepas aktiviti, Ali dapati satu botol tiada label. Apakah tindakan yang betul?', ['Serahkan kepada guru tanpa membukanya', 'Hidu untuk mengetahuinya', 'Simpan untuk kegunaan lain', 'Buang ke dalam singki'], 0,
        'Bahan yang tidak dikenali tidak boleh dihidu, digunakan atau dibuang sesuka hati kerana ia mungkin berbahaya.'),
      m('Kenapa singki bukan tempat membuang semua sisa aktiviti?', ['Sesetengah bahan mencemarkan air', 'Singki mudah tersumbat sahaja', 'Air jadi sejuk', 'Singki jadi kotor sahaja'], 0,
        'Bahan kimia yang masuk ke dalam saluran air boleh mencemarkan sungai dan membahayakan hidupan.'),
      m('Peraturan manakah yang melindungi murid LAIN, bukan diri sendiri?', ['Membersihkan meja selepas aktiviti', 'Memakai cermin mata', 'Memakai apron', 'Mengikat rambut'], 0,
        'Cermin mata, apron dan rambut terikat melindungi diri sendiri. Meja yang bersih melindungi orang yang menggunakannya selepas kita.'),
      m('Seorang murid mengikut semua peraturan tetapi tidak memberitahu guru tentang luka kecil. Apakah masalahnya?', ['Bahan boleh masuk melalui luka terbuka', 'Luka itu nampak hodoh', 'Guru akan marah', 'Luka menjadikan tangan berat'], 0,
        'Kulit yang pecah membenarkan bahan masuk ke dalam badan, jadi luka kecil pun perlu ditutup sebelum menyentuh bahan.')
    ]
  },

  // ------------------------------ 3. Benda Hidup dan Benda Bukan Hidup
  {
    mudah: [
      m('Manakah antara berikut benda hidup?', ['Kucing', 'Batu', 'Kerusi', 'Cawan'], 0,
        'Kucing bernafas, makan dan membesar, jadi ia benda hidup.'),
      m('Manakah antara berikut benda BUKAN hidup?', ['Meja', 'Pokok', 'Burung', 'Ikan'], 0,
        'Meja tidak bernafas, tidak makan dan tidak membesar.'),
      m('Semua benda hidup perlu apa untuk terus hidup?', ['Makanan', 'Kereta', 'Televisyen', 'Buku'], 0,
        'Makanan memberi tenaga kepada semua benda hidup.'),
      m('Adakah pokok benda hidup?', ['Ya', 'Tidak', 'Kadang-kadang', 'Hanya waktu siang'], 0,
        'Pokok membesar, memerlukan air dan udara, dan boleh membiak. Ia benda hidup.'),
      m('Benda hidup boleh membesar. Manakah yang BOLEH membesar?', ['Anak ayam', 'Bola', 'Pensel', 'Pintu'], 0,
        'Anak ayam membesar menjadi ayam dewasa. Bola, pensel dan pintu kekal sama.'),
      m('Manakah keperluan asas semua benda hidup?', ['Udara', 'Wang', 'Telefon', 'Kasut'], 0,
        'Semua benda hidup perlu udara untuk bernafas.'),
      m('Ikan bergerak di dalam air. Adakah ikan benda hidup?', ['Ya', 'Tidak', 'Hanya di laut', 'Hanya waktu malam'], 0,
        'Ikan bergerak sendiri, bernafas dan membesar, jadi ia benda hidup.'),
      m('Manakah antara berikut TIDAK memerlukan makanan?', ['Basikal', 'Anjing', 'Rumput', 'Ayam'], 0,
        'Basikal ialah benda bukan hidup, jadi ia tidak makan.'),
      m('Benda hidup boleh membiak. Apakah maksud membiak?', ['Menghasilkan anak', 'Menjadi berat', 'Bertukar warna', 'Menjadi sejuk'], 0,
        'Membiak bermakna menghasilkan hidupan baharu yang serupa dengannya.'),
      m('Manakah kumpulan yang SEMUANYA benda hidup?', ['Kucing, pokok, ikan', 'Kucing, batu, ikan', 'Meja, pokok, ikan', 'Batu, cawan, pintu'], 0,
        'Kucing, pokok dan ikan ketiga-tiganya bernafas dan membesar.')
    ],
    sederhana: [
      m('Kenapa kereta BUKAN benda hidup walaupun ia bergerak?', ['Ia tidak membesar dan tidak membiak', 'Ia terlalu besar', 'Ia berwarna', 'Ia bising'], 0,
        'Bergerak sahaja tidak cukup. Benda hidup mesti membesar, membiak, bernafas dan memerlukan makanan.'),
      m('Manakah ciri yang ADA pada benda hidup sahaja?', ['Bernafas', 'Berwarna', 'Berat', 'Keras'], 0,
        'Batu juga berwarna, berat dan keras. Hanya benda hidup yang bernafas.'),
      i('Daripada senarai ini, berapa banyak benda hidup: kucing, batu, pokok, meja, ikan?', 3,
        'Benda hidup ialah kucing, pokok dan ikan. Itu 3.'),
      m('Sebiji telur menetas menjadi anak ayam. Apakah ciri benda hidup yang ditunjukkan?', ['Membiak', 'Bertukar warna', 'Menjadi berat', 'Bergerak sahaja'], 0,
        'Telur yang menetas menunjukkan ayam menghasilkan hidupan baharu, iaitu membiak.'),
      m('Kenapa pokok dianggap benda hidup walaupun ia tidak berjalan?', ['Ia membesar, bernafas dan membiak', 'Ia hijau', 'Ia tinggi', 'Ia berdaun'], 0,
        'Berjalan bukan syarat benda hidup. Membesar, bernafas dan membiak adalah cirinya.'),
      m('Ali menyiram pokok setiap hari. Kenapa?', ['Pokok perlukan air untuk hidup', 'Supaya pokok bersih', 'Supaya pokok sejuk', 'Supaya tanah berat'], 0,
        'Air ialah salah satu keperluan asas semua benda hidup.'),
      m('Manakah pasangan yang BETUL?', ['Rama-rama hidup, batu bukan hidup', 'Rama-rama bukan hidup, batu hidup', 'Kedua-duanya hidup', 'Kedua-duanya bukan hidup'], 0,
        'Rama-rama bernafas dan membiak. Batu tidak melakukan apa-apa daripada itu.'),
      m('Sebiji benih tumbuh menjadi pokok kecil. Ciri apakah ini?', ['Membesar', 'Membiak', 'Bergerak', 'Bernafas'], 0,
        'Bertukar daripada kecil kepada besar ialah membesar.'),
      m('Kenapa robot mainan BUKAN benda hidup?', ['Ia tidak membesar atau membiak', 'Ia bergerak laju', 'Ia berwarna', 'Ia mahal'], 0,
        'Robot bergerak kerana bateri, bukan kerana ia hidup. Ia tidak membesar dan tidak membiak.'),
      m('Manakah kumpulan yang SEMUANYA benda bukan hidup?', ['Batu, cawan, kerusi', 'Batu, cawan, ikan', 'Pokok, cawan, kerusi', 'Batu, ayam, kerusi'], 0,
        'Batu, cawan dan kerusi ketiga-tiganya tidak bernafas dan tidak membesar.')
    ],
    cabaran: [
      m('Sebatang kayu di dalam rumah tidak membesar. Adakah ia benda hidup?', ['Tidak, kerana ia sudah mati', 'Ya, kerana ia daripada pokok', 'Ya, kerana ia berwarna coklat', 'Tidak, kerana ia keras'], 0,
        'Kayu memang datang daripada pokok yang hidup, tetapi selepas ditebang ia tidak lagi bernafas, membesar atau membiak.'),
      i('Ali ada 4 benda hidup dan 6 benda bukan hidup. Berapakah jumlah benda semuanya?', 10,
        '4 + 6 = 10 benda.'),
      m('Manakah ciri yang PALING pasti menunjukkan sesuatu itu benda hidup?', ['Ia boleh membiak', 'Ia bergerak', 'Ia berwarna', 'Ia berbunyi'], 0,
        'Kereta bergerak dan berbunyi, dan banyak benda bukan hidup berwarna. Hanya benda hidup yang boleh menghasilkan hidupan baharu.'),
      m('Sebiji telur belum menetas. Adakah ia benda hidup?', ['Ya, kerana ada anak ayam hidup di dalamnya', 'Tidak, kerana ia tidak bergerak', 'Tidak, kerana ia bulat', 'Ya, kerana ia licin'], 0,
        'Di dalam telur ada hidupan yang sedang membesar, jadi telur itu membawa benda hidup.'),
      m('Kenapa awan yang bergerak dan membesar BUKAN benda hidup?', ['Ia tidak bernafas, tidak makan dan tidak membiak', 'Ia terlalu tinggi', 'Ia berwarna putih', 'Ia ringan'], 0,
        'Awan membesar kerana wap air berkumpul, bukan kerana ia hidup. Ia tidak melakukan ciri hidup yang lain.'),
      i('Sebiji pokok menghasilkan 12 biji buah. Setiap buah ada 2 biji benih. Berapa biji benih semuanya?', 24,
        '12 × 2 = 24 biji benih.'),
      m('Ali meletakkan dua pasu, satu disiram dan satu tidak. Selepas seminggu, pokok yang tidak disiram layu. Apakah yang dibuktikan?', ['Benda hidup perlukan air', 'Pasu perlu dicuci', 'Tanah perlu ditukar', 'Pokok suka matahari'], 0,
        'Hanya air yang berbeza antara kedua-dua pasu, jadi air itulah sebab pokok satu lagi layu.'),
      m('Manakah pernyataan yang SALAH?', ['Semua benda yang bergerak adalah hidup', 'Semua benda hidup perlukan udara', 'Semua benda hidup membesar', 'Semua benda hidup membiak'], 0,
        'Kereta, awan dan air sungai bergerak tetapi bukan benda hidup. Tiga pernyataan lain memang benar.'),
      m('Kenapa manusia perlu makan setiap hari?', ['Untuk mendapat tenaga dan membesar', 'Untuk menjadi berat', 'Untuk bergerak sahaja', 'Untuk bercakap'], 0,
        'Makanan memberi tenaga untuk semua aktiviti badan dan bahan untuk membesar.'),
      m('Sebuah bilik ada 3 pasu bunga, 2 ekor ikan dan 5 buah kerusi. Berapa kumpulan benda hidup yang berbeza ada di situ?', ['2', '3', '1', '5'], 0,
        'Ada dua jenis benda hidup, iaitu bunga dan ikan. Kerusi bukan benda hidup.')
    ],
    ultra: [
      m('Seorang murid berkata "bulan bergerak, jadi bulan hidup." Apakah kesilapan dalam pemikirannya?', ['Dia menggunakan satu ciri sahaja, sedangkan benda hidup perlu semua ciri', 'Bulan terlalu jauh', 'Bulan berwarna putih', 'Bulan hanya nampak malam'], 0,
        'Satu ciri tidak cukup. Benda hidup mesti bernafas, makan, membesar dan membiak, dan bulan tidak melakukan satu pun.'),
      m('Manakah yang membuktikan seekor haiwan itu hidup, walaupun ia sedang tidur dan tidak bergerak?', ['Ia bernafas', 'Ia berbulu', 'Ia berwarna', 'Ia berat'], 0,
        'Haiwan yang tidur tetap bernafas. Bulu, warna dan berat juga ada pada haiwan yang sudah mati.'),
      i('Sebuah taman ada 15 pokok. Sebanyak 6 pokok mati kerana kemarau. Berapa pokok hidup yang tinggal?', 9,
        '15 − 6 = 9 pokok masih hidup.'),
      m('Kenapa buah yang dipetik masih boleh dianggap pernah menjadi sebahagian benda hidup?', ['Ia tumbuh daripada pokok yang hidup', 'Ia berwarna cerah', 'Ia manis', 'Ia bulat'], 0,
        'Buah terbentuk daripada pokok yang hidup. Selepas dipetik ia tidak lagi membesar, tetapi asalnya daripada hidupan.'),
      m('Dua bekas ditutup rapat. Satu ada tumbuhan, satu ada batu. Selepas beberapa hari tumbuhan layu. Apakah sebab yang paling munasabah?', ['Tumbuhan kehabisan udara dan cahaya', 'Batu menyerap air', 'Bekas terlalu kecil', 'Tumbuhan terlalu berat'], 0,
        'Benda hidup memerlukan udara dan cahaya. Batu tidak berubah kerana ia tidak memerlukan apa-apa.'),
      m('Manakah senarai yang disusun daripada PALING pasti hidup kepada paling pasti bukan hidup?', ['Ayam, benih, batu', 'Batu, ayam, benih', 'Benih, batu, ayam', 'Batu, benih, ayam'], 0,
        'Ayam jelas hidup kerana ia bernafas dan bergerak. Benih hidup tetapi tidak menunjukkannya sehingga ia tumbuh. Batu jelas bukan hidup.'),
      i('Sebuah akuarium ada 8 ekor ikan. Setiap ikan memerlukan 2 liter air. Berapa liter air diperlukan semuanya?', 16,
        '8 × 2 = 16 liter.'),
      m('Kenapa kita tidak boleh menilai sesuatu itu hidup hanya kerana ia berwarna cerah?', ['Banyak benda bukan hidup juga berwarna cerah', 'Warna cerah menyakitkan mata', 'Benda hidup tiada warna', 'Warna berubah setiap hari'], 0,
        'Bola, kereta dan bunga plastik semuanya berwarna cerah tetapi bukan benda hidup.'),
      m('Sebiji benih disimpan dalam bekas kering selama setahun, kemudian ditanam dan tumbuh. Apakah yang ditunjukkan?', ['Benih itu hidup walaupun kelihatan tidak aktif', 'Benih itu mati kemudian hidup semula', 'Tanah menghidupkan benih', 'Air menciptakan hidupan baharu'], 0,
        'Benih itu hidup sepanjang masa, cuma ia berehat sehingga mendapat air dan tanah yang sesuai.'),
      m('Manakah perbandingan yang PALING tepat antara pokok dan kerusi kayu?', ['Pokok membesar dan membiak, kerusi tidak', 'Kedua-duanya membesar', 'Kedua-duanya bernafas', 'Kerusi membiak dengan kayu baharu'], 0,
        'Kerusi memang dibuat daripada kayu pokok, tetapi ia tidak lagi menjalankan ciri hidup.')
    ]
  },

  // ------------------------------------------------------------ 4. Manusia
  {
    mudah: [
      m('Organ manakah memberi kita deria penglihatan?', ['Mata', 'Telinga', 'Hidung', 'Lidah'], 0,
        'Mata ialah organ untuk melihat.'),
      m('Organ manakah memberi kita deria pendengaran?', ['Telinga', 'Mata', 'Kulit', 'Lidah'], 0,
        'Telinga ialah organ untuk mendengar.'),
      m('Organ manakah memberi kita deria bau?', ['Hidung', 'Lidah', 'Mata', 'Kulit'], 0,
        'Hidung ialah organ untuk menghidu.'),
      m('Organ manakah memberi kita deria rasa?', ['Lidah', 'Hidung', 'Telinga', 'Mata'], 0,
        'Lidah ialah organ untuk merasa.'),
      m('Organ manakah memberi kita deria sentuh?', ['Kulit', 'Mata', 'Telinga', 'Lidah'], 0,
        'Kulit menutupi seluruh badan dan merasa sentuhan.'),
      i('Berapakah bilangan organ deria pada manusia?', 5,
        'Ada lima organ deria: mata, telinga, hidung, lidah dan kulit.'),
      m('Kita tahu makanan itu masin dengan organ apa?', ['Lidah', 'Hidung', 'Mata', 'Telinga'], 0,
        'Masin ialah satu rasa, dan rasa dikesan oleh lidah.'),
      m('Kita tahu bunga itu wangi dengan organ apa?', ['Hidung', 'Mata', 'Lidah', 'Kulit'], 0,
        'Wangi ialah bau, dan bau dikesan oleh hidung.'),
      m('Kita tahu air itu sejuk dengan organ apa?', ['Kulit', 'Mata', 'Telinga', 'Hidung'], 0,
        'Sejuk dan panas dirasai melalui kulit.'),
      m('Apakah yang perlu kita buat untuk menjaga mata?', ['Membaca dengan cahaya yang cukup', 'Membaca dalam gelap', 'Menggosok mata dengan tangan kotor', 'Melihat matahari terus'], 0,
        'Cahaya yang cukup mengurangkan tekanan pada mata.')
    ],
    sederhana: [
      m('Ali menutup hidungnya lalu makan epal. Kenapa rasanya kurang jelas?', ['Bau membantu kita mengenal rasa', 'Epal jadi sejuk', 'Lidah berhenti berfungsi', 'Epal jadi keras'], 0,
        'Bau dan rasa bekerja bersama. Apabila hidung ditutup, makanan terasa hambar.'),
      m('Rina berdiri di dalam bilik gelap. Deria manakah paling banyak membantunya bergerak?', ['Sentuh', 'Penglihatan', 'Rasa', 'Bau'], 0,
        'Dalam gelap mata tidak berguna, jadi dia meraba dengan tangan, iaitu deria sentuh.'),
      m('Kenapa kita tidak patut mendengar muzik yang sangat kuat?', ['Ia boleh merosakkan telinga', 'Ia membuang bateri', 'Ia membuat lidah kering', 'Ia menyakitkan mata'], 0,
        'Bunyi yang terlalu kuat merosakkan bahagian dalam telinga.'),
      i('Ali menggunakan mata dan telinga untuk menonton wayang. Berapa organ deria yang dia guna?', 2,
        'Mata untuk melihat dan telinga untuk mendengar. Itu 2 organ deria.'),
      m('Siti memegang bekas dan terus melepaskannya. Apakah kemungkinan besar yang berlaku?', ['Bekas itu terlalu panas', 'Bekas itu berwarna merah', 'Bekas itu berbunyi', 'Bekas itu berbau'], 0,
        'Kulit merasa panas dan menghantar amaran supaya tangan dilepaskan dengan cepat.'),
      m('Manakah pasangan organ dan deria yang SALAH?', ['Kulit dan penglihatan', 'Mata dan penglihatan', 'Telinga dan pendengaran', 'Lidah dan rasa'], 0,
        'Kulit memberi deria sentuh, bukan penglihatan.'),
      m('Kenapa kita perlu membasuh tangan sebelum makan?', ['Kuman pada tangan boleh masuk ke mulut', 'Tangan jadi wangi', 'Makanan jadi sedap', 'Tangan jadi sejuk'], 0,
        'Tangan menyentuh banyak benda, dan kuman padanya boleh masuk ke badan melalui makanan.'),
      m('Ali mendengar bunyi kereta sebelum melihatnya. Apakah yang ditunjukkan?', ['Deria pendengaran boleh memberi amaran awal', 'Kereta itu laju', 'Mata Ali rosak', 'Bunyi lebih penting daripada penglihatan'], 0,
        'Telinga mengesan bunyi walaupun benda itu belum kelihatan, jadi ia memberi amaran lebih awal.'),
      m('Kenapa kita perlu memotong kuku dengan kerap?', ['Kotoran dan kuman berkumpul di bawah kuku', 'Kuku jadi cantik sahaja', 'Kuku jadi ringan', 'Jari jadi panjang'], 0,
        'Kuku panjang menyimpan kotoran yang boleh masuk ke mulut.'),
      m('Manakah cara MENJAGA telinga yang betul?', ['Tidak memasukkan benda tajam ke dalamnya', 'Membersihkan dengan pensel', 'Mendengar bunyi kuat setiap hari', 'Menutup telinga sepanjang masa'], 0,
        'Benda tajam boleh mengoyakkan bahagian dalam telinga.')
    ],
    cabaran: [
      m('Ali dapat mengenal kawan dari jauh sebelum kawannya bercakap. Deria manakah yang dia guna?', ['Penglihatan', 'Pendengaran', 'Bau', 'Sentuh'], 0,
        'Kawannya belum bercakap, jadi bukan pendengaran. Dari jauh, mata yang mengenalnya.'),
      i('Manusia ada 5 deria. Jika seorang murid menutup mata dan hidung, berapa deria yang masih boleh dia guna?', 3,
        '5 − 2 = 3 deria, iaitu pendengaran, rasa dan sentuh.'),
      m('Kenapa orang selesema sukar merasa makanan?', ['Hidung tersumbat, jadi bau tidak dikesan', 'Lidah menjadi kecil', 'Gigi menjadi lemah', 'Mulut menjadi kering'], 0,
        'Rasa bergantung banyak pada bau. Hidung yang tersumbat menghilangkan sebahagian besar rasa.'),
      m('Seorang murid buta boleh membaca dengan jarinya. Deria manakah yang menggantikan penglihatan?', ['Sentuh', 'Bau', 'Rasa', 'Pendengaran'], 0,
        'Huruf Braille ialah bintik timbul yang dirasa dengan hujung jari, iaitu deria sentuh.'),
      m('Rina memegang dua bekas air. Satu terasa panas, satu sejuk. Deria dan organ manakah yang terlibat?', ['Sentuh, kulit', 'Rasa, lidah', 'Bau, hidung', 'Penglihatan, mata'], 0,
        'Panas dan sejuk dirasai oleh kulit tangan, iaitu deria sentuh.'),
      m('Kenapa deria sentuh ada di seluruh badan, bukan di satu tempat sahaja?', ['Kulit menutupi seluruh badan', 'Sentuhan lebih penting', 'Badan perlu berat', 'Kulit berwarna'], 0,
        'Organ deria sentuh ialah kulit, dan kulit membalut seluruh badan.'),
      i('Ali membasuh tangan 6 kali sehari selama 5 hari. Berapa kali semuanya?', 30,
        '6 × 5 = 30 kali.'),
      m('Manakah aktiviti yang menggunakan PALING banyak deria?', ['Makan sambil menonton televisyen', 'Membaca buku senyap', 'Mendengar radio dalam gelap', 'Memegang batu dengan mata tertutup'], 0,
        'Makan menggunakan rasa, bau dan sentuh, dan menonton menambah penglihatan dan pendengaran.'),
      m('Kenapa kita perlu berhenti membaca sebentar setiap 30 minit?', ['Supaya mata berehat', 'Supaya buku sejuk', 'Supaya tangan kuat', 'Supaya bilik terang'], 0,
        'Mata yang bekerja tanpa henti menjadi letih dan kabur.'),
      m('Seorang murid tidak dapat mengesan bau asap. Apakah bahaya yang paling besar?', ['Dia tidak sedar ada kebakaran', 'Dia tidak dapat makan', 'Dia tidak dapat melihat', 'Dia tidak dapat berjalan'], 0,
        'Bau asap ialah amaran awal kebakaran. Tanpa deria bau, amaran itu hilang.')
    ],
    ultra: [
      m('Dua orang murid merasa air yang sama. Seorang kata masin, seorang kata hambar. Apakah sebab yang paling munasabah?', ['Seorang daripada mereka baru makan sesuatu yang mengubah rasa', 'Air itu bertukar semasa dirasa', 'Lidah satu daripada mereka rosak kekal', 'Air masin hanya pada waktu petang'], 0,
        'Makanan sebelumnya boleh meninggalkan rasa di lidah dan mengubah cara air itu dirasa.'),
      m('Kenapa deria bekerja lebih baik apabila digunakan bersama?', ['Setiap deria memberi maklumat berbeza yang saling melengkapi', 'Deria bersaing antara satu sama lain', 'Satu deria melemahkan yang lain', 'Deria hanya berfungsi berpasangan'], 0,
        'Mata memberi rupa, telinga memberi bunyi, hidung memberi bau. Digabungkan, gambaran menjadi lengkap.'),
      i('Seorang murid tidur 9 jam setiap malam. Berapa jam dia tidur dalam seminggu?', 63,
        '9 × 7 = 63 jam.'),
      m('Manakah kenyataan yang PALING tepat tentang kulit?', ['Kulit ialah organ deria yang paling luas', 'Kulit hanya merasa sakit', 'Kulit tidak merasa suhu', 'Kulit hanya ada pada tangan'], 0,
        'Kulit menutup seluruh badan, jadi ia organ deria terbesar, dan ia merasa sentuhan, suhu dan sakit.'),
      m('Kenapa kita menarik tangan dengan cepat daripada benda panas sebelum sempat berfikir?', ['Badan memberi tindak balas segera untuk melindungi diri', 'Tangan menjadi ringan', 'Benda panas menolak tangan', 'Kulit menjadi licin'], 0,
        'Tindak balas pantas ini melindungi kulit daripada kecederaan yang lebih teruk.'),
      m('Seorang murid pekak sebelah telinga. Apakah yang paling sukar untuknya?', ['Mengetahui arah datangnya bunyi', 'Melihat warna', 'Merasa makanan', 'Menghidu bau'], 0,
        'Dua telinga membandingkan bunyi untuk menentukan arah. Dengan satu telinga sahaja, arah menjadi sukar.'),
      i('Manusia mempunyai 5 deria. Sebuah kelas ada 30 murid. Berapakah jumlah organ deria dalam kelas itu?', 150,
        '30 × 5 = 150 organ deria.'),
      m('Kenapa doktor memeriksa mata, telinga dan tekak semasa pemeriksaan kesihatan?', ['Ia laluan biasa masuknya kuman dan tanda awal penyakit', 'Ia bahagian yang cantik', 'Ia mudah dilihat sahaja', 'Ia bahagian yang berat'], 0,
        'Bahagian itu terbuka kepada udara luar, jadi tanda penyakit selalunya muncul di situ dahulu.'),
      m('Manakah situasi yang menunjukkan satu deria memberi amaran yang deria lain terlepas?', ['Menghidu gas bocor yang tidak kelihatan', 'Melihat bola berwarna', 'Mendengar muzik kegemaran', 'Merasa gula-gula manis'], 0,
        'Gas bocor tidak boleh dilihat atau didengar, tetapi hidung dapat mengesannya dan menyelamatkan nyawa.'),
      m('Kenapa menjaga kebersihan diri termasuk dalam pelajaran sains?', ['Ia melindungi organ badan daripada kuman dan kerosakan', 'Ia menjadikan kita nampak kemas sahaja', 'Ia menjimatkan wang', 'Ia peraturan sekolah sahaja'], 0,
        'Kebersihan menghalang kuman memasuki badan melalui mata, hidung, mulut dan kulit.')
    ]
  },

  // ------------------------------------------------------------- 5. Haiwan
  {
    mudah: [
      m('Bahagian tubuh manakah membolehkan burung terbang?', ['Sayap', 'Kaki', 'Paruh', 'Ekor'], 0,
        'Sayap menolak udara ke bawah dan mengangkat burung ke atas.'),
      m('Bahagian tubuh manakah membolehkan ikan berenang?', ['Sirip', 'Sayap', 'Kaki', 'Telinga'], 0,
        'Sirip menolak air dan mengemudi ikan.'),
      m('Haiwan manakah mempunyai empat kaki?', ['Kucing', 'Burung', 'Ikan', 'Ular'], 0,
        'Kucing berjalan dengan empat kaki.'),
      m('Apakah kegunaan paruh burung?', ['Mengambil makanan', 'Terbang', 'Berenang', 'Mendengar'], 0,
        'Paruh digunakan untuk mematuk dan mengambil makanan.'),
      m('Haiwan manakah TIADA kaki?', ['Ular', 'Ayam', 'Kambing', 'Arnab'], 0,
        'Ular bergerak dengan mengengsot badannya, tanpa kaki.'),
      m('Bahagian tubuh manakah digunakan kucing untuk mendengar?', ['Telinga', 'Ekor', 'Kaki', 'Bulu'], 0,
        'Telinga kucing mengesan bunyi, sama seperti telinga manusia.'),
      m('Haiwan manakah mempunyai dua kaki?', ['Ayam', 'Kucing', 'Lembu', 'Kambing'], 0,
        'Ayam berjalan dengan dua kaki.'),
      m('Apakah kegunaan ekor ikan?', ['Menolak badan ke hadapan', 'Bernafas', 'Melihat', 'Makan'], 0,
        'Ekor ikan bergerak ke kiri dan kanan untuk menolak badannya ke hadapan.'),
      m('Haiwan manakah mempunyai bulu pelepah?', ['Burung', 'Ikan', 'Ular', 'Katak'], 0,
        'Hanya burung mempunyai bulu pelepah.'),
      m('Apakah kegunaan kaki katak yang berselaput?', ['Membantu berenang', 'Membantu terbang', 'Membantu mendengar', 'Membantu melihat'], 0,
        'Selaput di antara jari menolak air seperti dayung.')
    ],
    sederhana: [
      m('Kenapa ikan mempunyai badan yang licin dan tirus?', ['Supaya mudah bergerak dalam air', 'Supaya nampak cantik', 'Supaya berat', 'Supaya panas'], 0,
        'Bentuk tirus membelah air dengan mudah, jadi ikan bergerak laju.'),
      m('Kenapa burung mempunyai tulang yang ringan?', ['Supaya senang terbang', 'Supaya senang berenang', 'Supaya senang berjalan', 'Supaya senang makan'], 0,
        'Badan yang ringan lebih mudah diangkat ke udara oleh sayap.'),
      i('Seekor kucing ada 4 kaki. Berapa kaki yang ada pada 5 ekor kucing?', 20,
        '5 × 4 = 20 kaki.'),
      m('Ular tiada kaki tetapi boleh bergerak laju. Bagaimana?', ['Dengan mengengsot badannya', 'Dengan melompat', 'Dengan terbang', 'Dengan berenang sahaja'], 0,
        'Ular menolak badannya pada tanah dengan gerakan berombak.'),
      m('Kenapa ayam mempunyai kuku yang kuat pada kakinya?', ['Untuk mengais tanah mencari makanan', 'Untuk berenang', 'Untuk terbang tinggi', 'Untuk mendengar'], 0,
        'Ayam mengais tanah dengan kukunya untuk mencari cacing dan biji.'),
      m('Bahagian manakah membantu kucing mengekalkan keseimbangan semasa melompat?', ['Ekor', 'Telinga', 'Kumis', 'Bulu'], 0,
        'Ekor bergerak untuk menyeimbangkan badan semasa kucing melompat.'),
      i('Seekor burung ada 2 sayap. Berapa sayap yang ada pada 7 ekor burung?', 14,
        '7 × 2 = 14 sayap.'),
      m('Kenapa arnab mempunyai telinga yang panjang?', ['Untuk mendengar bahaya dari jauh', 'Untuk terbang', 'Untuk berenang', 'Untuk makan'], 0,
        'Telinga panjang mengumpul lebih banyak bunyi, jadi arnab dapat mengesan pemangsa lebih awal.'),
      m('Manakah pasangan haiwan dan bahagian tubuh yang SALAH?', ['Ikan dan sayap', 'Burung dan paruh', 'Kucing dan kumis', 'Katak dan kaki berselaput'], 0,
        'Ikan mempunyai sirip, bukan sayap.'),
      m('Kenapa itik boleh berenang tetapi ayam tidak?', ['Kaki itik berselaput', 'Itik lebih besar', 'Itik lebih ringan', 'Ayam takut air'], 0,
        'Selaput pada kaki itik menolak air seperti dayung. Kaki ayam tidak berselaput.')
    ],
    cabaran: [
      m('Seekor haiwan mempunyai sayap tetapi tidak boleh terbang. Manakah contohnya?', ['Ayam', 'Burung merpati', 'Helang', 'Burung layang-layang'], 0,
        'Ayam mempunyai sayap tetapi badannya terlalu berat dan sayapnya terlalu kecil untuk terbang jauh.'),
      i('Sebuah reban ada 12 ekor ayam. Berapa jumlah kaki semuanya?', 24,
        '12 × 2 = 24 kaki, kerana setiap ayam ada 2 kaki.'),
      m('Kenapa haiwan yang hidup di air biasanya mempunyai sirip dan bukan kaki?', ['Sirip lebih sesuai untuk menolak air', 'Kaki terlalu berat', 'Sirip lebih cantik', 'Kaki mudah patah'], 0,
        'Sirip yang luas dan rata menolak banyak air, manakala kaki dibuat untuk menolak tanah.'),
      m('Seekor haiwan bergerak dengan melompat dan mempunyai kaki belakang yang panjang. Haiwan manakah itu?', ['Katak', 'Ikan', 'Ular', 'Burung hantu'], 0,
        'Kaki belakang yang panjang menghasilkan tolakan kuat untuk melompat jauh.'),
      i('Seekor kucing ada 4 kaki dan seekor ayam ada 2 kaki. Berapa jumlah kaki bagi 3 kucing dan 4 ayam?', 20,
        'Kucing: 3 × 4 = 12 kaki. Ayam: 4 × 2 = 8 kaki. Jumlah = 12 + 8 = 20 kaki.'),
      m('Kenapa burung hantu mempunyai mata yang besar?', ['Untuk melihat dengan lebih baik pada waktu malam', 'Untuk terbang laju', 'Untuk mendengar', 'Untuk makan'], 0,
        'Mata besar mengumpul lebih banyak cahaya, jadi burung hantu nampak dalam gelap.'),
      m('Manakah kumpulan haiwan yang SEMUANYA berkaki empat?', ['Kucing, lembu, kambing', 'Kucing, ayam, lembu', 'Ular, kambing, kucing', 'Ikan, lembu, kambing'], 0,
        'Kucing, lembu dan kambing ketiga-tiganya berjalan dengan empat kaki.'),
      m('Kenapa ikan tidak boleh hidup lama di darat?', ['Insangnya hanya boleh mengambil udara daripada air', 'Ia tidak boleh berjalan', 'Ia terlalu licin', 'Ia terlalu sejuk'], 0,
        'Insang perlu basah untuk berfungsi. Di darat ia kering dan ikan tidak dapat bernafas.'),
      m('Seekor haiwan mempunyai bulu, dua kaki dan paruh. Apakah kumpulannya?', ['Burung', 'Ikan', 'Mamalia', 'Reptilia'], 0,
        'Bulu pelepah, dua kaki dan paruh ialah ciri burung.'),
      m('Kenapa gajah mempunyai belalai yang panjang?', ['Untuk mengambil makanan dan air', 'Untuk berenang', 'Untuk terbang', 'Untuk mendengar'], 0,
        'Belalai berfungsi seperti tangan untuk mencapai daun tinggi dan menyedut air.')
    ],
    ultra: [
      m('Dua ekor haiwan hidup di padang pasir yang panas. Ciri manakah paling membantu mereka?', ['Boleh menyimpan air dalam badan', 'Bulu yang tebal', 'Sirip yang besar', 'Kaki berselaput'], 0,
        'Air jarang ditemui di padang pasir, jadi menyimpan air ialah kelebihan terbesar. Sirip dan kaki berselaput berguna dalam air, bukan pasir.'),
      i('Sebuah zoo ada 8 ekor burung, 5 ekor kucing dan 3 ekor ular. Berapa jumlah kaki semua haiwan itu?', 36,
        'Burung: 8 × 2 = 16. Kucing: 5 × 4 = 20. Ular tiada kaki. Jumlah = 16 + 20 = 36 kaki.'),
      m('Kenapa haiwan yang diburu selalunya mempunyai mata di tepi kepala?', ['Supaya dapat melihat ke banyak arah sekali gus', 'Supaya nampak comel', 'Supaya kepala ringan', 'Supaya boleh berenang'], 0,
        'Mata di tepi memberi pandangan luas untuk mengesan pemangsa yang datang dari mana-mana arah.'),
      m('Seekor katak boleh hidup di darat dan dalam air. Ciri manakah membolehkannya?', ['Kulit lembap dan kaki berselaput', 'Bulu tebal', 'Paruh keras', 'Sisik kering'], 0,
        'Kulit lembap membantunya bernafas di darat, dan kaki berselaput membantunya berenang.'),
      m('Kenapa bentuk paruh burung berbeza-beza?', ['Setiap bentuk sesuai untuk jenis makanan yang berbeza', 'Untuk membezakan jantina', 'Untuk terbang lebih laju', 'Untuk membuat bunyi'], 0,
        'Paruh tajam untuk mengoyak daging, paruh leper untuk menapis air, paruh pendek kuat untuk memecah biji.'),
      i('Seekor lembu ada 4 kaki. Sebuah ladang ada 25 ekor lembu, tetapi 3 ekor dijual. Berapa jumlah kaki lembu yang tinggal?', 88,
        'Lembu tinggal = 25 − 3 = 22. Kaki = 22 × 4 = 88.'),
      m('Manakah kesimpulan yang PALING tepat tentang bahagian tubuh haiwan?', ['Bentuknya sesuai dengan tempat tinggal dan cara hidupnya', 'Semuanya sama sahaja', 'Bentuknya berubah setiap hari', 'Bentuknya bergantung pada warna'], 0,
        'Ikan mendapat sirip kerana ia hidup dalam air, burung mendapat sayap kerana ia terbang. Bentuk mengikut keperluan.'),
      m('Kenapa haiwan pemangsa seperti helang mempunyai kuku yang tajam dan melengkung?', ['Untuk mencengkam mangsa supaya tidak terlepas', 'Untuk berjalan di tanah', 'Untuk berenang', 'Untuk memanjat pokok sahaja'], 0,
        'Kuku melengkung mengunci mangsa semasa helang terbang membawanya.'),
      m('Sebuah kolam mengering. Haiwan manakah paling terjejas?', ['Ikan', 'Burung', 'Kucing', 'Arnab'], 0,
        'Ikan bernafas melalui insang yang perlu air. Burung, kucing dan arnab boleh berpindah mencari air lain.'),
      m('Kenapa arnab mempunyai kaki belakang yang lebih kuat daripada kaki hadapan?', ['Untuk melompat jauh melarikan diri', 'Untuk menggali sahaja', 'Untuk berenang', 'Untuk memanjat'], 0,
        'Kaki belakang yang kuat memberi tolakan besar, jadi arnab boleh melompat pantas daripada bahaya.')
    ]
  },

  // ----------------------------------------------------------- 6. Tumbuhan
  {
    mudah: [
      m('Bahagian tumbuhan manakah menyerap air dari tanah?', ['Akar', 'Daun', 'Bunga', 'Buah'], 0,
        'Akar berada di dalam tanah dan menyerap air.'),
      m('Bahagian tumbuhan manakah membuat makanan?', ['Daun', 'Akar', 'Batang', 'Buah'], 0,
        'Daun menggunakan cahaya matahari untuk membuat makanan.'),
      m('Bahagian tumbuhan manakah menyokong pokok supaya berdiri tegak?', ['Batang', 'Daun', 'Bunga', 'Akar'], 0,
        'Batang menegakkan pokok dan menyokong daun serta bunga.'),
      m('Bahagian tumbuhan manakah selalunya berwarna dan wangi?', ['Bunga', 'Akar', 'Batang', 'Daun'], 0,
        'Bunga berwarna dan wangi untuk menarik serangga.'),
      m('Apakah yang diperlukan tumbuhan daripada langit?', ['Cahaya matahari', 'Bunyi', 'Angin sahaja', 'Warna'], 0,
        'Cahaya matahari diperlukan daun untuk membuat makanan.'),
      m('Bahagian tumbuhan manakah mengandungi biji benih?', ['Buah', 'Akar', 'Daun', 'Batang'], 0,
        'Biji benih terkandung di dalam buah.'),
      m('Apakah yang berlaku kepada pokok yang tidak disiram?', ['Ia layu', 'Ia membesar', 'Ia berbunga', 'Ia berbuah'], 0,
        'Tanpa air, pokok tidak dapat hidup dan akan layu.'),
      m('Manakah bahagian tumbuhan yang berada di DALAM tanah?', ['Akar', 'Daun', 'Bunga', 'Buah'], 0,
        'Akar tumbuh ke bawah ke dalam tanah.'),
      i('Berapakah bahagian utama tumbuhan berbunga: akar, batang, daun dan bunga?', 4,
        'Ada 4 bahagian utama yang disenaraikan.'),
      m('Melalui bahagian manakah air bergerak dari akar ke daun?', ['Batang', 'Bunga', 'Buah', 'Biji'], 0,
        'Batang mengandungi salur yang membawa air ke atas.')
    ],
    sederhana: [
      m('Kenapa daun kebanyakan tumbuhan berwarna hijau?', ['Warna hijau membantu daun menyerap cahaya', 'Hijau lebih cantik', 'Hijau lebih sejuk', 'Hijau lebih berat'], 0,
        'Bahan hijau dalam daun menangkap cahaya matahari untuk membuat makanan.'),
      m('Kenapa akar tumbuh ke bawah, bukan ke atas?', ['Air dan zat ada di dalam tanah', 'Tanah lebih ringan', 'Ke atas terlalu panas', 'Ke bawah lebih gelap'], 0,
        'Akar mencari air dan zat makanan, dan kedua-duanya ada di dalam tanah.'),
      i('Sebuah pasu mempunyai 3 pokok. Setiap pokok ada 8 helai daun. Berapa helai daun semuanya?', 24,
        '3 × 8 = 24 helai daun.'),
      m('Ali meletakkan pokok di dalam almari gelap selama seminggu. Apakah yang akan berlaku?', ['Daunnya menjadi pucat dan pokok lemah', 'Pokok membesar cepat', 'Pokok berbunga', 'Pokok berbuah'], 0,
        'Tanpa cahaya, daun tidak dapat membuat makanan, jadi pokok menjadi lemah dan pucat.'),
      m('Kenapa bunga mempunyai bau yang wangi?', ['Untuk menarik serangga', 'Untuk menakutkan haiwan', 'Untuk menyerap air', 'Untuk menyokong batang'], 0,
        'Serangga yang datang membantu bunga menghasilkan buah dan biji.'),
      m('Manakah pasangan bahagian dan fungsinya yang BETUL?', ['Akar dan menyerap air', 'Daun dan menyerap air', 'Bunga dan menyokong pokok', 'Batang dan membuat makanan'], 0,
        'Akar menyerap air, daun membuat makanan, batang menyokong dan bunga menarik serangga.'),
      m('Kenapa pokok di dalam rumah perlu diletakkan berhampiran tingkap?', ['Supaya mendapat cahaya matahari', 'Supaya nampak cantik', 'Supaya senang disiram', 'Supaya angin masuk'], 0,
        'Cahaya matahari diperlukan daun untuk membuat makanan.'),
      i('Ali menyiram 5 pasu bunga setiap hari selama 6 hari. Berapa kali dia menyiram semuanya?', 30,
        '5 × 6 = 30 kali.'),
      m('Apakah yang berlaku jika akar sebuah pokok dipotong semuanya?', ['Pokok tidak dapat menyerap air dan akan mati', 'Pokok membesar lebih cepat', 'Pokok berbunga', 'Pokok menjadi lebih tinggi'], 0,
        'Tanpa akar, tiada air masuk ke dalam pokok.'),
      m('Kenapa tumbuhan penting kepada manusia dan haiwan?', ['Ia memberi makanan dan udara bersih', 'Ia memberi warna sahaja', 'Ia memberi bunyi', 'Ia memberi cahaya'], 0,
        'Tumbuhan menghasilkan makanan dan membebaskan udara yang kita hidu.')
    ],
    cabaran: [
      m('Dua pasu diletakkan di tempat sama dan disiram sama. Satu ditutup dengan kotak gelap. Apakah yang berbeza selepas seminggu?', ['Pokok dalam kotak menjadi pucat', 'Kedua-duanya sama', 'Pokok dalam kotak lebih hijau', 'Pokok dalam kotak berbuah'], 0,
        'Hanya cahaya yang berbeza, jadi kesannya mesti datang daripada ketiadaan cahaya.'),
      i('Sebuah kebun ada 9 baris pokok. Setiap baris ada 6 pokok. Berapa pokok semuanya?', 54,
        '9 × 6 = 54 pokok.'),
      m('Kenapa pokok besar mempunyai akar yang besar dan dalam?', ['Untuk memegang pokok supaya tidak tumbang', 'Untuk menyimpan buah', 'Untuk membuat makanan', 'Untuk menarik serangga'], 0,
        'Akar yang besar mencengkam tanah dan menahan pokok daripada tumbang ditiup angin.'),
      m('Seorang murid memetik semua daun sebuah pokok kecil. Apakah kesan yang paling teruk?', ['Pokok tidak dapat membuat makanan', 'Pokok menjadi ringan', 'Pokok menjadi pendek', 'Pokok berbau'], 0,
        'Daun ialah tempat makanan dibuat. Tanpa daun, pokok kelaparan.'),
      i('Sebuah pokok menghasilkan 15 biji buah. Setiap buah mengandungi 4 biji benih. Berapa biji benih semuanya?', 60,
        '15 × 4 = 60 biji benih.'),
      m('Kenapa tumbuhan di dalam hutan tebal tumbuh tinggi dan lurus?', ['Untuk mencapai cahaya matahari di atas', 'Untuk kelihatan cantik', 'Untuk menyerap air lebih banyak', 'Untuk mengelak haiwan'], 0,
        'Cahaya di bawah hutan sangat sedikit, jadi pokok berlumba tumbuh tinggi untuk mendapatkannya.'),
      m('Manakah urutan yang BETUL bagi pergerakan air dalam tumbuhan?', ['Akar, batang, daun', 'Daun, batang, akar', 'Batang, akar, daun', 'Bunga, akar, daun'], 0,
        'Air diserap oleh akar, naik melalui batang, dan sampai ke daun.'),
      m('Sebuah pokok diletakkan di tepi tingkap. Selepas sebulan, batangnya membengkok ke arah tingkap. Kenapa?', ['Pokok tumbuh ke arah cahaya', 'Tingkap menarik pokok', 'Angin menolak pokok', 'Tanah bergerak'], 0,
        'Tumbuhan tumbuh ke arah cahaya kerana daun memerlukannya untuk membuat makanan.'),
      m('Kenapa petani menggemburkan tanah sebelum menanam?', ['Supaya akar mudah menembusi dan udara masuk', 'Supaya tanah cantik', 'Supaya tanah berat', 'Supaya tanah sejuk'], 0,
        'Tanah yang gembur membenarkan akar tumbuh dan udara serta air meresap masuk.'),
      m('Manakah yang BUKAN keperluan asas tumbuhan?', ['Bunyi', 'Air', 'Cahaya matahari', 'Udara'], 0,
        'Tumbuhan perlukan air, cahaya, udara dan zat tanah. Bunyi tidak diperlukan.')
    ],
    ultra: [
      m('Dua pokok sama ditanam. Satu di tanah gembur, satu di tanah keras berbatu. Manakah tumbuh lebih baik dan kenapa?', ['Tanah gembur, kerana akar dan udara mudah bergerak', 'Tanah berbatu, kerana lebih kukuh', 'Kedua-duanya sama', 'Tanah berbatu, kerana lebih sejuk'], 0,
        'Akar memerlukan ruang untuk memanjang dan udara untuk bernafas. Tanah keras menghalang kedua-duanya.'),
      i('Sebuah ladang menanam 8 baris pokok, setiap baris 12 pokok. Sebanyak 16 pokok mati. Berapa pokok yang hidup?', 80,
        'Jumlah asal = 8 × 12 = 96. Yang hidup = 96 − 16 = 80 pokok.'),
      m('Kenapa daun tumbuhan di kawasan panas dan kering selalunya kecil atau berduri?', ['Untuk mengurangkan kehilangan air', 'Untuk kelihatan berbeza', 'Untuk menyerap lebih banyak cahaya', 'Untuk menarik serangga'], 0,
        'Permukaan daun yang kecil kehilangan lebih sedikit air, jadi tumbuhan bertahan lebih lama tanpa hujan.'),
      m('Seorang murid berkata "pokok makan tanah kerana tanah berkurangan." Apakah kesilapannya?', ['Pokok membuat makanan sendiri di daun, bukan memakan tanah', 'Tanah tidak pernah berkurangan', 'Pokok makan air sahaja', 'Pokok makan udara sahaja'], 0,
        'Tanah memberi air dan sedikit zat, tetapi makanan sebenar dibuat oleh daun menggunakan cahaya matahari.'),
      m('Kenapa hutan yang ditebang menyebabkan tanah runtuh?', ['Tiada akar yang memegang tanah', 'Tanah menjadi panas', 'Tanah menjadi ringan', 'Hujan menjadi lebat'], 0,
        'Akar pokok mengikat tanah. Apabila pokok hilang, hujan mudah menghanyutkan tanah.'),
      i('Setiap pokok menghasilkan 25 helai daun sebulan. Berapa helai daun dihasilkan 6 pokok dalam 2 bulan?', 300,
        'Sebulan: 6 × 25 = 150 helai. Dua bulan: 150 × 2 = 300 helai.'),
      m('Manakah bukti PALING kuat bahawa daun membuat makanan?', ['Pokok tanpa daun akan mati walaupun disiram', 'Daun berwarna hijau', 'Daun berbau', 'Daun mudah gugur'], 0,
        'Kalau air sudah cukup tetapi pokok tetap mati tanpa daun, bermakna daun melakukan sesuatu yang penting yang air tidak boleh gantikan.'),
      m('Kenapa bunga yang tidak dilawati serangga selalunya tidak menghasilkan buah?', ['Serangga membantu proses menghasilkan biji', 'Serangga menyiram bunga', 'Serangga memberi cahaya', 'Serangga memakan daun'], 0,
        'Serangga memindahkan debunga antara bunga, dan tanpa itu biji tidak terbentuk.'),
      m('Sebuah pokok diletakkan dalam bekas kaca tertutup dengan air dan cahaya. Ia hidup berbulan-bulan. Apakah yang ditunjukkan?', ['Tumbuhan boleh mengitar semula udara dan air dalam ruang tertutup', 'Tumbuhan tidak perlukan udara', 'Kaca memberi makanan', 'Air menjadi makanan'], 0,
        'Tumbuhan membebaskan udara yang ia sendiri perlukan semula, dan air yang tersejat kembali menjadi titisan.'),
      m('Manakah kesimpulan yang PALING tepat tentang bahagian tumbuhan?', ['Setiap bahagian mempunyai tugas yang berbeza tetapi saling bergantung', 'Semua bahagian melakukan tugas yang sama', 'Hanya daun yang penting', 'Hanya akar yang penting'], 0,
        'Akar memberi air kepada daun, daun memberi makanan kepada seluruh pokok, dan batang menghubungkan kedua-duanya.')
    ]
  },

  // -------------------------------------------------------------- 7. Magnet
  {
    mudah: [
      m('Apakah yang boleh dilakukan magnet?', ['Menarik besi', 'Menarik kertas', 'Menarik kaca', 'Menarik kayu'], 0,
        'Magnet menarik bahan yang mengandungi besi.'),
      m('Manakah bahan yang DITARIK oleh magnet?', ['Paku besi', 'Pemadam getah', 'Pensel kayu', 'Cawan plastik'], 0,
        'Paku besi mengandungi besi, jadi ia ditarik magnet.'),
      m('Manakah bahan yang TIDAK ditarik oleh magnet?', ['Kertas', 'Klip kertas besi', 'Paku', 'Gunting besi'], 0,
        'Kertas tidak mengandungi besi, jadi magnet tidak menariknya.'),
      m('Berapakah bilangan kutub pada sebatang magnet?', ['2', '1', '3', '4'], 0,
        'Setiap magnet ada dua kutub, iaitu utara dan selatan.'),
      m('Apakah nama dua kutub magnet?', ['Utara dan selatan', 'Atas dan bawah', 'Kiri dan kanan', 'Panas dan sejuk'], 0,
        'Kutub magnet dinamakan utara dan selatan.'),
      m('Apakah yang berlaku apabila kutub utara didekatkan dengan kutub utara?', ['Ia menolak', 'Ia menarik', 'Ia melekat', 'Tiada apa berlaku'], 0,
        'Kutub yang sama menolak antara satu sama lain.'),
      m('Apakah yang berlaku apabila kutub utara didekatkan dengan kutub selatan?', ['Ia menarik', 'Ia menolak', 'Ia pecah', 'Tiada apa berlaku'], 0,
        'Kutub yang berlainan menarik antara satu sama lain.'),
      m('Manakah alat yang menggunakan magnet?', ['Kompas', 'Pembaris', 'Pensel', 'Buku'], 0,
        'Jarum kompas ialah magnet kecil yang menunjuk ke arah utara.'),
      m('Bahan manakah paling banyak ditarik magnet?', ['Besi', 'Plastik', 'Kaca', 'Getah'], 0,
        'Besi ialah bahan yang paling kuat ditarik magnet.'),
      m('Bolehkah magnet menarik melalui sekeping kertas nipis?', ['Boleh', 'Tidak boleh', 'Hanya jika basah', 'Hanya jika berwarna'], 0,
        'Tarikan magnet boleh menembusi bahan nipis seperti kertas.')
    ],
    sederhana: [
      i('Ali menguji 10 objek dengan magnet. Sebanyak 4 objek ditarik. Berapa objek yang TIDAK ditarik?', 6,
        '10 − 4 = 6 objek tidak ditarik.'),
      m('Kenapa klip kertas melekat pada magnet tetapi butang plastik tidak?', ['Klip kertas diperbuat daripada besi', 'Klip kertas lebih kecil', 'Klip kertas lebih ringan', 'Klip kertas berwarna'], 0,
        'Magnet hanya menarik bahan yang mengandungi besi.'),
      m('Rina mendekatkan dua magnet dan ia menolak antara satu sama lain. Apakah yang berlaku?', ['Kutub yang sama bertemu', 'Magnet itu rosak', 'Magnet terlalu kecil', 'Magnet terlalu sejuk'], 0,
        'Kutub sama sentiasa menolak. Untuk menarik, satu magnet perlu dipusing.'),
      m('Kenapa jarum kompas sentiasa menunjuk ke arah yang sama?', ['Bumi sendiri bertindak seperti magnet besar', 'Jarum itu berat', 'Jarum itu panjang', 'Jarum itu berwarna'], 0,
        'Bumi mempunyai medan magnet, dan jarum kompas sejajar dengannya.'),
      m('Manakah cara terbaik untuk mengumpul paku yang bertaburan di lantai?', ['Guna magnet', 'Guna kertas', 'Guna air', 'Guna kain'], 0,
        'Magnet menarik paku besi dengan cepat dan selamat tanpa perlu menyentuhnya.'),
      i('Sebatang magnet ada 2 kutub. Berapa jumlah kutub pada 7 batang magnet?', 14,
        '7 × 2 = 14 kutub.'),
      m('Manakah pernyataan yang BETUL?', ['Magnet menarik besi tetapi bukan plastik', 'Magnet menarik semua logam', 'Magnet menarik kertas', 'Magnet menarik air'], 0,
        'Magnet menarik besi. Bukan semua logam ditarik, dan plastik, kertas serta air tidak ditarik langsung.'),
      m('Ali meletakkan magnet di bawah meja nipis dan klip di atasnya. Klip bergerak. Apakah yang ditunjukkan?', ['Tarikan magnet boleh menembusi bahan nipis', 'Meja itu magnet', 'Klip itu hidup', 'Meja itu besi'], 0,
        'Daya magnet bertindak melalui bahan nipis seperti kayu atau kertas.'),
      m('Kenapa pintu peti sejuk melekat rapat apabila ditutup?', ['Ada magnet pada tepinya', 'Ia sejuk', 'Ia berat', 'Ia licin'], 0,
        'Jalur magnet pada tepi pintu menariknya rapat kepada badan besi peti sejuk.'),
      m('Manakah kumpulan yang SEMUANYA ditarik magnet?', ['Paku, klip besi, gunting besi', 'Paku, kertas, klip besi', 'Getah, paku, plastik', 'Kaca, kayu, kertas'], 0,
        'Ketiga-tiga objek dalam pilihan pertama mengandungi besi.')
    ],
    cabaran: [
      m('Sebatang magnet dipotong dua. Berapa kutub yang ada pada setiap bahagian?', ['2', '1', '0', '4'], 0,
        'Setiap kepingan magnet, walau sekecil mana, tetap mempunyai kutub utara dan selatan.'),
      i('Ali menguji 24 objek. Satu pertiga daripadanya ditarik magnet. Berapa objek yang ditarik?', 8,
        '24 ÷ 3 = 8 objek ditarik.'),
      m('Rina meletakkan magnet berhampiran timbunan pasir bercampur serbuk besi. Apakah yang berlaku?', ['Serbuk besi melekat pada magnet, pasir tinggal', 'Semuanya melekat', 'Tiada apa melekat', 'Hanya pasir melekat'], 0,
        'Magnet memilih hanya bahan berasaskan besi, jadi ia memisahkan serbuk besi daripada pasir.'),
      m('Kenapa magnet tidak sesuai diletakkan berhampiran kad bank atau jam?', ['Ia boleh merosakkan bahagian dalamnya', 'Ia menjadikan kad panas', 'Ia menjadikan kad berat', 'Ia menukar warna kad'], 0,
        'Medan magnet boleh memadam maklumat pada jalur kad dan mengganggu bahagian halus dalam jam.'),
      m('Dua magnet diletakkan berdekatan dan ia melekat. Apakah yang pasti berlaku?', ['Kutub berlainan yang bertemu', 'Kedua-duanya kutub utara', 'Kedua-duanya kutub selatan', 'Magnet itu rosak'], 0,
        'Hanya kutub berlainan yang menarik. Kalau kutub sama, ia akan menolak.'),
      i('Sebuah kotak ada 30 objek. Sebanyak 12 diperbuat daripada besi. Berapa objek yang TIDAK akan ditarik magnet?', 18,
        '30 − 12 = 18 objek.'),
      m('Kenapa kompas tidak berguna berhampiran magnet yang kuat?', ['Magnet itu menarik jarum lebih kuat daripada Bumi', 'Kompas jadi berat', 'Kompas jadi panas', 'Jarum jadi pendek'], 0,
        'Jarum menunjuk kepada daya magnet paling kuat berdekatan, dan magnet yang rapat lebih kuat daripada Bumi.'),
      m('Ali menggosok paku dengan magnet berulang kali ke satu arah. Apakah yang mungkin berlaku?', ['Paku itu menjadi magnet lemah', 'Paku itu menjadi panas', 'Paku itu menjadi pendek', 'Paku itu bertukar warna'], 0,
        'Menggosok ke satu arah menyusun bahagian dalam besi sehingga paku itu sendiri menjadi magnet.'),
      m('Manakah pernyataan yang SALAH?', ['Magnet menarik semua benda berkilat', 'Magnet ada dua kutub', 'Kutub sama menolak', 'Magnet menarik besi'], 0,
        'Berkilat tidak bermakna berasaskan besi. Aluminium dan kaca berkilat tetapi tidak ditarik magnet.'),
      m('Kenapa magnet berguna di tapak pelupusan besi buruk?', ['Ia mengangkat besi dan meninggalkan bahan lain', 'Ia memotong besi', 'Ia membakar sampah', 'Ia menimbang sampah'], 0,
        'Magnet besar mengangkat hanya bahan berasaskan besi, jadi ia memisahkan besi daripada sampah lain dengan cepat.')
    ],
    ultra: [
      m('Sebatang magnet dipotong kepada 4 bahagian. Berapa jumlah kutub pada kesemua bahagian?', ['8', '2', '4', '6'], 0,
        'Setiap bahagian menjadi magnet lengkap dengan 2 kutub. 4 × 2 = 8 kutub.'),
      m('Ali mahu memisahkan klip besi daripada butang plastik yang bercampur. Cara manakah PALING cepat dan bersih?', ['Lalukan magnet di atas campuran itu', 'Asingkan satu demi satu dengan tangan', 'Tuang ke dalam air', 'Tiup campuran itu'], 0,
        'Magnet mengangkat semua klip sekali gus dan tidak menyentuh butang plastik langsung.'),
      i('Sebuah magnet boleh mengangkat 15 klip. Berapa klip boleh diangkat oleh 4 magnet yang sama kuat?', 60,
        '4 × 15 = 60 klip.'),
      m('Kenapa dua magnet yang menolak akan menarik jika satu daripadanya dipusing?', ['Memusing menukar kutub yang bertemu', 'Memusing menjadikan magnet lebih kuat', 'Memusing menjadikan magnet panas', 'Memusing menambah kutub'], 0,
        'Sebelum dipusing, kutub sama bertemu dan menolak. Selepas dipusing, kutub berlainan bertemu dan menarik.'),
      m('Manakah eksperimen yang PALING baik untuk menguji kekuatan dua magnet?', ['Kira berapa klip setiap magnet boleh angkat', 'Lihat warna kedua-duanya', 'Timbang kedua-duanya', 'Ukur panjang kedua-duanya'], 0,
        'Bilangan klip yang diangkat mengukur daya tarikan secara terus. Warna, berat dan panjang tidak menunjukkan kekuatan magnet.'),
      m('Kenapa daya magnet menjadi lemah apabila jarak bertambah?', ['Daya magnet paling kuat rapat dengan magnet', 'Udara memakan daya itu', 'Magnet menjadi sejuk', 'Objek menjadi berat'], 0,
        'Kesan magnet berkurangan dengan cepat apabila jarak bertambah, jadi objek yang jauh tidak tertarik.'),
      i('Ali menguji 50 objek. Sebanyak 40% ditarik magnet. Berapa objek yang ditarik?', 20,
        '40% daripada 50 = 20 objek.'),
      m('Sebuah kompas diletakkan di atas meja besi. Kenapa bacaannya mungkin salah?', ['Meja besi mengganggu arah jarum', 'Meja terlalu tinggi', 'Meja terlalu licin', 'Meja terlalu berat'], 0,
        'Besi berdekatan mengubah arah medan magnet di sekeliling jarum, jadi ia tidak lagi menunjuk ke utara sebenar.'),
      m('Manakah kesimpulan yang PALING tepat selepas menguji banyak bahan dengan magnet?', ['Hanya bahan yang mengandungi besi ditarik', 'Semua logam ditarik', 'Semua benda keras ditarik', 'Semua benda berat ditarik'], 0,
        'Aluminium dan tembaga ialah logam tetapi tidak ditarik. Kayu keras dan batu berat juga tidak ditarik.'),
      m('Kenapa magnet digunakan pada pintu almari dan bukan selak biasa pada sesetengah perabot?', ['Ia menutup sendiri dan tiada bahagian yang mudah patah', 'Ia lebih murah sahaja', 'Ia lebih berat', 'Ia lebih berwarna'], 0,
        'Magnet menarik pintu rapat tanpa bahagian bergerak, jadi ia tahan lama dan senang digunakan kanak-kanak.')
    ]
  },

  // ---------------------------------------------------------- 8. Penyerapan
  {
    mudah: [
      m('Apakah maksud bahan yang menyerap air?', ['Air masuk ke dalam bahan itu', 'Air melantun daripadanya', 'Air bertukar warna', 'Air menjadi panas'], 0,
        'Menyerap bermakna air meresap masuk ke dalam bahan itu.'),
      m('Manakah bahan yang MENYERAP air?', ['Tuala', 'Plastik', 'Kaca', 'Besi'], 0,
        'Tuala menyerap air, itulah sebab ia digunakan untuk mengeringkan badan.'),
      m('Manakah bahan yang TIDAK menyerap air?', ['Plastik', 'Span', 'Kertas tisu', 'Kain'], 0,
        'Plastik tidak membenarkan air masuk, jadi ia tidak menyerap.'),
      m('Kenapa kita guna span untuk mengelap air yang tumpah?', ['Span menyerap banyak air', 'Span berwarna', 'Span ringan', 'Span murah'], 0,
        'Span mempunyai banyak lubang kecil yang memerangkap air.'),
      m('Manakah bahan yang paling sesuai dibuat payung?', ['Kain kalis air', 'Kertas tisu', 'Span', 'Tuala'], 0,
        'Payung mesti menghalang air, jadi ia perlu bahan yang tidak menyerap.'),
      m('Apakah yang berlaku kepada kertas tisu yang dicelup ke dalam air?', ['Ia menyerap air dan menjadi lembap', 'Ia kekal kering', 'Ia menjadi keras', 'Ia bertukar warna sahaja'], 0,
        'Kertas tisu mempunyai ruang kecil yang menyedut air masuk.'),
      m('Manakah bahan yang sesuai dibuat baju hujan?', ['Plastik', 'Tuala', 'Span', 'Kertas'], 0,
        'Plastik tidak menyerap air, jadi badan kekal kering.'),
      m('Kenapa tuala mandi diperbuat daripada kain tebal?', ['Supaya menyerap lebih banyak air', 'Supaya berat', 'Supaya panas', 'Supaya cantik'], 0,
        'Kain tebal mempunyai lebih banyak ruang untuk memerangkap air.'),
      m('Manakah bahan yang menyerap air paling BANYAK?', ['Span', 'Kaca', 'Besi', 'Plastik'], 0,
        'Span penuh dengan lubang kecil yang boleh diisi air.'),
      m('Kenapa bumbung rumah tidak diperbuat daripada kertas?', ['Kertas menyerap air dan mudah rosak', 'Kertas terlalu mahal', 'Kertas terlalu berat', 'Kertas terlalu keras'], 0,
        'Kertas yang menyerap hujan akan lembik dan koyak.')
    ],
    sederhana: [
      i('Ali menguji 12 bahan. Sebanyak 7 menyerap air. Berapa bahan yang tidak menyerap?', 5,
        '12 − 7 = 5 bahan tidak menyerap.'),
      m('Kenapa air tumpah di atas meja plastik mudah dilap?', ['Air kekal di permukaan kerana plastik tidak menyerap', 'Plastik menolak air', 'Plastik memanaskan air', 'Air menjadi ringan'], 0,
        'Air yang tidak meresap masuk kekal di atas dan senang dikumpul.'),
      m('Rina meletakkan sekeping kain dan sekeping plastik di dalam air. Apakah yang berbeza?', ['Kain menjadi berat kerana menyerap air', 'Plastik menjadi berat', 'Kedua-duanya sama', 'Kedua-duanya kekal kering'], 0,
        'Air yang diserap kain menambah beratnya. Plastik tidak menyerap, jadi beratnya kekal.'),
      m('Kenapa kain yang basah lebih berat daripada kain kering?', ['Air yang diserap menambah berat', 'Kain mengembang', 'Kain menjadi tebal', 'Air menjadi berat'], 0,
        'Air yang masuk ke dalam kain ada beratnya sendiri.'),
      m('Manakah pasangan yang BETUL?', ['Span menyerap, kaca tidak menyerap', 'Span tidak menyerap, kaca menyerap', 'Kedua-duanya menyerap', 'Kedua-duanya tidak menyerap'], 0,
        'Span berlubang dan menyerap. Kaca licin dan rapat, jadi ia tidak menyerap.'),
      m('Kenapa payung yang berlubang tidak berguna?', ['Air masuk melalui lubang itu', 'Payung menjadi berat', 'Payung menjadi panas', 'Payung menjadi kecil'], 0,
        'Payung berfungsi kerana ia menghalang laluan air. Lubang membatalkan halangan itu.'),
      i('Sekeping span kering beratnya 20 g. Selepas menyerap air, beratnya 90 g. Berapa gram air yang diserap?', 70,
        '90 − 20 = 70 g air.'),
      m('Kenapa lampin bayi diperbuat daripada bahan yang sangat menyerap?', ['Supaya kulit bayi kekal kering', 'Supaya lampin berat', 'Supaya lampin berwarna', 'Supaya lampin panas'], 0,
        'Bahan itu menyedut cecair jauh daripada kulit bayi.'),
      m('Ali mahu menyimpan air di dalam bekas. Bahan manakah yang sesuai?', ['Plastik', 'Kertas', 'Kain', 'Span'], 0,
        'Bekas mesti tidak menyerap dan tidak bocor, jadi plastik sesuai.'),
      m('Kenapa baju yang dijemur di bawah matahari cepat kering?', ['Haba matahari menyejatkan air dalam kain', 'Matahari menyerap kain', 'Angin menyerap kain', 'Kain menjadi tebal'], 0,
        'Haba menukar air menjadi wap yang meninggalkan kain.')
    ],
    cabaran: [
      i('Tiga span menyerap 60 ml, 45 ml dan 75 ml air. Berapa jumlah air yang diserap semuanya, dalam ml?', 180,
        '60 + 45 + 75 = 180 ml.'),
      m('Ali meletakkan kertas tisu dan kain pada air yang sama banyak. Kertas tisu menjadi lembap dahulu. Apakah maksudnya?', ['Kertas tisu menyerap lebih cepat', 'Kain tidak menyerap', 'Air lebih suka kertas', 'Kertas lebih berat'], 0,
        'Bahan yang menjadi lembap dahulu ialah yang menyedut air lebih cepat.'),
      m('Kenapa kasut kulit dilapisi bahan kalis air?', ['Supaya air tidak meresap masuk ke dalam kasut', 'Supaya kasut cantik', 'Supaya kasut ringan', 'Supaya kasut sejuk'], 0,
        'Lapisan itu menghalang air, jadi kaki kekal kering walaupun berjalan di tempat basah.'),
      i('Sekeping kain menyerap 25 ml air. Berapa ml air diserap oleh 6 keping kain yang sama?', 150,
        '6 × 25 = 150 ml.'),
      m('Rina menuang air ke atas dua permukaan: satu kayu tidak bersalut dan satu kayu bersalut varnis. Apakah yang berbeza?', ['Air meresap masuk pada kayu tidak bersalut', 'Air meresap pada kayu bersalut', 'Kedua-duanya sama', 'Air menjadi panas'], 0,
        'Varnis menutup liang kayu, jadi air kekal di permukaan.'),
      m('Kenapa tuala basah tidak dapat mengeringkan tangan dengan baik?', ['Ia sudah penuh air, jadi tidak boleh menyerap lagi', 'Ia menjadi keras', 'Ia menjadi sejuk', 'Ia menjadi ringan'], 0,
        'Ruang dalam kain sudah diisi air, jadi tiada tempat untuk air baharu masuk.'),
      m('Manakah bahan paling sesuai untuk membuat khemah?', ['Kain kalis air', 'Kertas tisu', 'Span', 'Kain tuala'], 0,
        'Khemah mesti menghalang hujan sambil kekal ringan, jadi kain kalis air sesuai.'),
      i('Sebuah span menyerap 80 ml air. Selepas diperah, 55 ml keluar. Berapa ml air yang masih tinggal dalam span?', 25,
        '80 − 55 = 25 ml.'),
      m('Kenapa lantai bilik air dibuat daripada jubin dan bukan kayu biasa?', ['Jubin tidak menyerap air jadi tidak reput', 'Jubin lebih murah', 'Jubin lebih ringan', 'Jubin lebih panas'], 0,
        'Kayu yang sentiasa menyerap air akan reput dan berkulat.'),
      m('Ali hendak menguji bahan manakah menyerap paling banyak. Apakah yang MESTI sama dalam ujiannya?', ['Saiz bahan dan jumlah air', 'Warna bahan', 'Nama bahan', 'Tempat ujian sahaja'], 0,
        'Kalau saiz atau jumlah air berbeza, kita tidak tahu sama ada perbezaan datang daripada bahan atau daripada saiz.')
    ],
    ultra: [
      i('Tiga bahan menyerap air: A 40 ml, B 65 ml, C 25 ml. Berapa beza antara yang paling banyak dan paling sedikit, dalam ml?', 40,
        'Paling banyak B 65 ml, paling sedikit C 25 ml. Beza = 65 − 25 = 40 ml.'),
      m('Kenapa bahan yang berliang halus menyerap lebih banyak air daripada bahan padat?', ['Liang itu memberi ruang untuk air masuk', 'Liang menjadikan bahan berat', 'Liang menarik air seperti magnet', 'Liang memanaskan air'], 0,
        'Air mengisi ruang kosong di dalam bahan. Bahan padat tiada ruang itu.'),
      m('Sebuah bumbung bocor. Bahan manakah PALING buruk untuk menampalnya?', ['Kertas', 'Plastik tebal', 'Getah', 'Logam nipis'], 0,
        'Kertas menyerap air dan hancur. Tiga bahan lain menghalang air.'),
      i('Sebuah tuala menyerap 120 ml air. Ia diperah tiga kali, setiap kali mengeluarkan 35 ml. Berapa ml air yang tinggal?', 15,
        'Air keluar = 3 × 35 = 105 ml. Tinggal = 120 − 105 = 15 ml.'),
      m('Kenapa pasu bunga mempunyai lubang di bawah?', ['Supaya air berlebihan keluar dan akar tidak reput', 'Supaya pasu ringan', 'Supaya tanah keluar', 'Supaya udara masuk sahaja'], 0,
        'Tanah yang sentiasa penuh air menghalang udara sampai ke akar, dan akar akan reput.'),
      m('Dua kain yang sama saiz diuji. Kain A menyerap 30 ml, kain B menyerap 30 ml tetapi lebih cepat. Manakah lebih sesuai untuk tuala tangan?', ['Kain B, kerana ia mengeringkan lebih cepat', 'Kain A, kerana lebih perlahan', 'Kedua-duanya sama sahaja', 'Tiada yang sesuai'], 0,
        'Kedua-duanya menampung jumlah sama, tetapi kelajuan menyerap menentukan seberapa cepat tangan menjadi kering.'),
      m('Kenapa bahan kalis air digunakan pada beg komputer riba?', ['Air boleh merosakkan bahagian elektrik di dalamnya', 'Beg jadi ringan', 'Beg jadi cantik', 'Beg jadi murah'], 0,
        'Air yang meresap masuk boleh merosakkan litar elektrik secara kekal.'),
      i('Setiap span menyerap 45 ml air. Berapa ml air diserap oleh 8 span, jika 2 daripadanya sudah basah dan tidak menyerap apa-apa?', 270,
        'Span yang menyerap = 8 − 2 = 6. Air = 6 × 45 = 270 ml.'),
      m('Manakah kesimpulan yang PALING tepat selepas menguji banyak bahan?', ['Bahan berliang menyerap, bahan padat dan licin tidak', 'Semua bahan lembut menyerap', 'Semua bahan berat menyerap', 'Semua bahan berwarna menyerap'], 0,
        'Yang menentukan ialah ada atau tidak ruang untuk air masuk, bukan lembut, berat atau warna.'),
      m('Kenapa jalan raya dibina supaya sedikit condong ke tepi?', ['Supaya air hujan mengalir keluar dan tidak bertakung', 'Supaya kereta laju', 'Supaya jalan cantik', 'Supaya jalan sejuk'], 0,
        'Jalan tidak menyerap air, jadi air mesti dialirkan keluar supaya tidak bertakung dan membahayakan kenderaan.')
    ]
  },

  // --------------------------------------------------------------- 9. Bumi
  {
    mudah: [
      m('Apakah yang kita nampak di langit pada waktu siang?', ['Matahari', 'Bulan penuh', 'Bintang', 'Lampu jalan'], 0,
        'Matahari kelihatan pada waktu siang dan memberi cahaya terang.'),
      m('Apakah yang kita nampak di langit pada waktu malam?', ['Bulan dan bintang', 'Matahari', 'Awan sahaja', 'Pelangi'], 0,
        'Bulan dan bintang kelihatan apabila langit gelap.'),
      m('Dari manakah datangnya cahaya pada waktu siang?', ['Matahari', 'Bulan', 'Bintang', 'Awan'], 0,
        'Matahari ialah sumber cahaya utama pada waktu siang.'),
      m('Apakah yang menutupi permukaan Bumi paling banyak?', ['Air', 'Tanah', 'Pasir', 'Batu'], 0,
        'Lebih banyak permukaan Bumi ditutupi air daripada tanah.'),
      m('Apakah yang kita perlukan daripada matahari?', ['Cahaya dan haba', 'Air', 'Tanah', 'Bunyi'], 0,
        'Matahari memberi cahaya untuk melihat dan haba untuk memanaskan Bumi.'),
      m('Bilakah kita paling mudah melihat bintang?', ['Malam yang cerah', 'Tengah hari', 'Pagi cerah', 'Petang cerah'], 0,
        'Cahaya matahari terlalu terang pada waktu siang, jadi bintang hanya kelihatan pada malam yang gelap.'),
      m('Apakah bentuk Bumi?', ['Bulat seperti bola', 'Rata seperti pinggan', 'Segi empat', 'Segi tiga'], 0,
        'Bumi berbentuk bulat seperti bola.'),
      m('Manakah yang memberi cahaya sendiri?', ['Matahari', 'Bulan', 'Bumi', 'Awan'], 0,
        'Matahari menghasilkan cahayanya sendiri. Bulan hanya memantulkan cahaya matahari.'),
      m('Apakah yang berlaku apabila matahari terbenam?', ['Hari menjadi gelap', 'Hari menjadi terang', 'Hujan turun', 'Angin berhenti'], 0,
        'Tanpa cahaya matahari, langit menjadi gelap dan malam bermula.'),
      m('Manakah sumber air di Bumi?', ['Sungai', 'Awan sahaja', 'Batu', 'Pasir'], 0,
        'Sungai, laut dan tasik ialah sumber air di Bumi.')
    ],
    sederhana: [
      m('Kenapa kita tidak nampak bintang pada waktu siang?', ['Cahaya matahari terlalu terang', 'Bintang hilang', 'Bintang tidur', 'Bintang jatuh'], 0,
        'Bintang tetap ada, tetapi cahaya matahari yang terang menenggelamkan cahaya bintang yang lemah.'),
      m('Kenapa bulan kelihatan bercahaya walaupun ia tidak menghasilkan cahaya?', ['Ia memantulkan cahaya matahari', 'Ia terbakar', 'Ia ada lampu', 'Ia berwarna putih'], 0,
        'Cahaya matahari mengenai bulan dan dipantulkan ke Bumi.'),
      i('Berapakah bilangan jam dalam sehari semalam?', 24,
        'Satu hari penuh mempunyai 24 jam.'),
      m('Kenapa air laut penting kepada Bumi?', ['Ia menjadi sumber hujan', 'Ia memberi cahaya', 'Ia memberi bunyi', 'Ia memberi warna'], 0,
        'Air laut yang tersejat membentuk awan, dan awan menurunkan hujan.'),
      m('Manakah yang PALING panas?', ['Matahari', 'Bulan', 'Bumi', 'Bintang jatuh'], 0,
        'Matahari sangat panas, dan haba itulah yang sampai ke Bumi.'),
      m('Kenapa kita perlu menjaga kebersihan sungai?', ['Air sungai digunakan manusia dan hidupan', 'Sungai nampak cantik sahaja', 'Sungai menjadi dalam', 'Sungai menjadi sejuk'], 0,
        'Sungai yang tercemar membahayakan manusia dan haiwan yang bergantung padanya.'),
      m('Ali keluar pada waktu tengah hari dan rasa sangat panas. Kenapa?', ['Matahari berada tinggi dan cahayanya paling kuat', 'Bumi menjadi kecil', 'Angin berhenti', 'Awan hilang selamanya'], 0,
        'Pada tengah hari cahaya matahari sampai paling tegak, jadi habanya paling kuat.'),
      m('Manakah pasangan yang BETUL?', ['Siang dan matahari', 'Siang dan bulan', 'Malam dan matahari', 'Malam dan pelangi'], 0,
        'Matahari kelihatan pada siang, bulan dan bintang pada malam.'),
      m('Kenapa kita memakai topi apabila keluar pada waktu panas?', ['Untuk melindungi kepala daripada cahaya matahari', 'Supaya nampak kemas', 'Supaya kepala berat', 'Supaya rambut panjang'], 0,
        'Topi menghalang cahaya matahari terus mengenai kepala dan muka.'),
      m('Manakah yang BUKAN terdapat di Bumi?', ['Api matahari', 'Air', 'Tanah', 'Udara'], 0,
        'Air, tanah dan udara ada di Bumi. Api matahari berada di matahari, bukan di Bumi.')
    ],
    cabaran: [
      m('Kenapa kawasan berhampiran laut selalunya lebih sejuk daripada kawasan jauh dari laut?', ['Air laut menyejukkan udara di sekitarnya', 'Laut lebih tinggi', 'Laut lebih gelap', 'Laut lebih dalam'], 0,
        'Air memanas dan menyejuk perlahan, jadi ia mengurangkan panas udara berhampiran.'),
      i('Dalam seminggu ada 7 hari. Berapakah jumlah jam dalam seminggu?', 168,
        '7 × 24 = 168 jam.'),
      m('Kenapa bayang-bayang kita panjang pada waktu pagi dan pendek pada tengah hari?', ['Kedudukan matahari berubah sepanjang hari', 'Badan kita berubah saiz', 'Tanah bergerak', 'Bayang menjadi berat'], 0,
        'Pagi matahari rendah, jadi bayang panjang. Tengah hari matahari tinggi, jadi bayang pendek.'),
      m('Kenapa Bumi sesuai untuk hidupan tetapi bulan tidak?', ['Bumi ada air dan udara', 'Bumi lebih besar', 'Bumi lebih dekat matahari', 'Bumi berwarna biru'], 0,
        'Hidupan memerlukan air dan udara. Bulan tiada kedua-duanya.'),
      m('Ali memerhati bahawa laut kelihatan biru. Apakah sebabnya?', ['Air memantulkan warna langit', 'Air memang berwarna biru pekat', 'Ikan berwarna biru', 'Pasir berwarna biru'], 0,
        'Air itu sendiri hampir jernih. Warna biru yang kita nampak sebahagian besarnya pantulan langit.'),
      i('Sebuah kampung mendapat hujan pada 12 hari dalam bulan yang ada 30 hari. Berapa hari TIDAK hujan?', 18,
        '30 − 12 = 18 hari tidak hujan.'),
      m('Kenapa hujan penting kepada Bumi?', ['Ia membekalkan air kepada hidupan dan tanah', 'Ia menyejukkan matahari', 'Ia membersihkan langit', 'Ia menggelapkan hari'], 0,
        'Hujan mengisi sungai, tasik dan tanah, dan semua hidupan bergantung pada air itu.'),
      m('Manakah kenyataan yang SALAH?', ['Bulan menghasilkan cahayanya sendiri', 'Matahari menghasilkan cahayanya sendiri', 'Bumi menerima cahaya matahari', 'Bintang menghasilkan cahaya sendiri'], 0,
        'Bulan tidak menghasilkan cahaya. Ia hanya memantulkan cahaya matahari.'),
      m('Kenapa kita tidak boleh memandang matahari secara terus?', ['Cahayanya boleh merosakkan mata', 'Ia terlalu jauh', 'Ia terlalu kecil', 'Ia berwarna kuning'], 0,
        'Cahaya matahari sangat kuat dan boleh membakar bahagian dalam mata secara kekal.'),
      m('Sebuah kawasan tidak menerima hujan selama berbulan-bulan. Apakah kesan yang paling teruk?', ['Tumbuhan mati dan sungai kering', 'Langit menjadi gelap', 'Bumi menjadi sejuk', 'Angin berhenti'], 0,
        'Tanpa air, tumbuhan mati, dan haiwan serta manusia yang bergantung padanya turut terjejas.')
    ],
    ultra: [
      m('Kenapa waktu siang dan malam berlaku silih berganti?', ['Bumi berputar, jadi satu bahagian menghadap matahari pada satu masa', 'Matahari padam pada waktu malam', 'Bulan menutup matahari setiap malam', 'Awan menutup matahari'], 0,
        'Bumi berputar pada paksinya. Bahagian yang menghadap matahari mengalami siang, bahagian bertentangan mengalami malam.'),
      i('Bumi berputar sekali dalam 24 jam. Berapa kali Bumi berputar dalam 5 hari?', 5,
        'Satu putaran sehari, jadi 5 hari bermakna 5 putaran.'),
      m('Kenapa kawasan gurun sangat panas pada siang tetapi sejuk pada malam?', ['Tiada air atau awan untuk menyimpan haba', 'Matahari lebih dekat', 'Pasir menghasilkan haba', 'Angin berhenti pada malam'], 0,
        'Air dan awan menyimpan haba. Gurun tiada kedua-duanya, jadi haba hilang dengan cepat selepas matahari terbenam.'),
      m('Manakah bukti PALING kuat bahawa bulan tidak menghasilkan cahaya sendiri?', ['Bahagian bulan yang gelap ialah bahagian yang tidak kena cahaya matahari', 'Bulan kelihatan putih', 'Bulan lebih kecil daripada matahari', 'Bulan hanya nampak pada malam'], 0,
        'Kalau bulan menghasilkan cahaya sendiri, seluruh permukaannya akan sentiasa bercahaya, bukan sebahagian sahaja.'),
      i('Sebuah bandar menerima 8 jam cahaya matahari sehari. Berapa jam cahaya matahari diterima dalam 3 minggu?', 168,
        '3 minggu = 21 hari. 21 × 8 = 168 jam.'),
      m('Kenapa pokok penting untuk menjaga Bumi?', ['Ia memberi udara bersih dan menahan tanah', 'Ia memberi cahaya', 'Ia memberi haba', 'Ia memberi bunyi'], 0,
        'Pokok membebaskan udara yang kita hidu, dan akarnya menahan tanah daripada dihanyutkan hujan.'),
      m('Dua kawasan menerima hujan yang sama. Satu berhutan, satu tandus. Manakah lebih mudah banjir?', ['Kawasan tandus, kerana tiada akar menyerap air', 'Kawasan berhutan, kerana pokok menahan air', 'Kedua-duanya sama', 'Bergantung pada warna tanah'], 0,
        'Akar pokok menyerap dan memperlahankan aliran air. Tanah tandus membiarkan air mengalir terus dan bertakung.'),
      m('Kenapa kita perlu menjimatkan air walaupun Bumi mempunyai banyak air?', ['Kebanyakan air Bumi ialah air laut yang tidak boleh diminum', 'Air akan habis esok', 'Air menjadi berat', 'Air menjadi panas'], 0,
        'Hanya sebahagian kecil air Bumi ialah air bersih yang boleh diminum.'),
      i('Sebuah keluarga menggunakan 150 liter air sehari. Berapa liter digunakan dalam 4 hari?', 600,
        '4 × 150 = 600 liter.'),
      m('Manakah tindakan yang PALING membantu menjaga Bumi?', ['Menanam pokok dan mengurangkan sampah', 'Membakar sampah di halaman', 'Membuang sampah ke sungai', 'Menebang pokok untuk ruang'], 0,
        'Menanam pokok menambah udara bersih dan mengurangkan sampah mengurangkan pencemaran. Tiga pilihan lain merosakkan alam.')
    ]
  },

  // -------------------------------------------------------- 10. Asas Binaan
  {
    mudah: [
      m('Manakah bentuk yang PALING kukuh untuk binaan?', ['Segi tiga', 'Bulatan', 'Bujur', 'Bintang'], 0,
        'Segi tiga tidak mudah berubah bentuk apabila ditolak, jadi ia paling kukuh.'),
      m('Apakah yang menyokong sebuah bangunan supaya berdiri tegak?', ['Tiang', 'Cat', 'Tingkap', 'Bumbung'], 0,
        'Tiang menanggung berat bangunan dan memindahkannya ke tanah.'),
      m('Manakah bahan yang kuat untuk membina rumah?', ['Batu bata', 'Kertas', 'Kain', 'Span'], 0,
        'Batu bata kuat dan tahan lama.'),
      m('Kenapa bangunan mempunyai asas di dalam tanah?', ['Supaya bangunan tidak tumbang', 'Supaya bangunan cantik', 'Supaya bangunan sejuk', 'Supaya bangunan ringan'], 0,
        'Asas memegang bangunan pada tanah supaya ia stabil.'),
      m('Manakah bentuk tapak yang PALING stabil?', ['Tapak yang lebar', 'Tapak yang sempit', 'Tapak yang tajam', 'Tapak yang bulat kecil'], 0,
        'Tapak yang lebar mengedarkan berat dan mengurangkan risiko tumbang.'),
      m('Apakah kegunaan bumbung?', ['Melindungi daripada hujan dan panas', 'Menyokong tiang', 'Menyimpan air', 'Menghias lantai'], 0,
        'Bumbung menghalang hujan dan cahaya matahari daripada masuk.'),
      m('Manakah binaan yang lebih stabil?', ['Menara pendek dan lebar', 'Menara tinggi dan kurus', 'Menara condong', 'Menara di atas bola'], 0,
        'Rendah dan lebar bermakna berat berada dekat tanah, jadi ia sukar tumbang.'),
      m('Kenapa jambatan perlu kuat?', ['Untuk menanggung berat kenderaan', 'Untuk kelihatan cantik', 'Untuk menyimpan air', 'Untuk menghalang angin'], 0,
        'Jambatan menanggung berat kenderaan yang melaluinya.'),
      m('Manakah bahan yang TIDAK sesuai untuk membina dinding rumah?', ['Kertas', 'Batu bata', 'Konkrit', 'Kayu'], 0,
        'Kertas terlalu lemah dan rosak apabila basah.'),
      m('Apakah yang berlaku jika tiang bangunan terlalu lemah?', ['Bangunan boleh runtuh', 'Bangunan menjadi tinggi', 'Bangunan menjadi sejuk', 'Bangunan menjadi cantik'], 0,
        'Tiang yang tidak mampu menanggung berat akan patah dan bangunan runtuh.')
    ],
    sederhana: [
      m('Kenapa struktur segi tiga digunakan pada bumbung dan jambatan?', ['Segi tiga tidak berubah bentuk apabila ditolak', 'Segi tiga lebih murah', 'Segi tiga lebih ringan', 'Segi tiga lebih cantik'], 0,
        'Segi empat boleh senget menjadi rombus apabila ditolak, tetapi segi tiga kekal bentuknya.'),
      i('Sebuah menara dibina daripada 5 lapis blok. Setiap lapis ada 4 blok. Berapa blok semuanya?', 20,
        '5 × 4 = 20 blok.'),
      m('Ali membina dua menara sama tinggi. Satu bertapak lebar, satu bertapak sempit. Manakah lebih mudah tumbang?', ['Bertapak sempit', 'Bertapak lebar', 'Kedua-duanya sama', 'Bergantung pada warna'], 0,
        'Tapak sempit menjadikan menara mudah hilang keseimbangan.'),
      m('Kenapa dinding rumah dibina lurus dan tegak?', ['Supaya berat turun terus ke tanah', 'Supaya cantik', 'Supaya senang dicat', 'Supaya rumah sejuk'], 0,
        'Dinding tegak memindahkan berat ke bawah dengan cekap. Dinding condong menerima daya sisi yang boleh meruntuhkannya.'),
      m('Manakah gabungan yang PALING kukuh?', ['Bahan kuat dan bentuk segi tiga', 'Bahan lemah dan bentuk segi tiga', 'Bahan kuat dan tapak sempit', 'Bahan lemah dan tapak sempit'], 0,
        'Kekukuhan datang daripada dua perkara sekali, iaitu bahan yang kuat dan bentuk yang stabil.'),
      i('Sebuah jambatan mainan menanggung 8 blok sebelum runtuh. Jambatan kedua menanggung 15 blok. Berapa blok lebih yang ditanggung jambatan kedua?', 7,
        '15 − 8 = 7 blok.'),
      m('Kenapa bangunan tinggi mempunyai asas yang sangat dalam?', ['Berat yang besar perlu disokong dengan kukuh', 'Supaya nampak tinggi', 'Supaya sejuk', 'Supaya ada ruang simpanan'], 0,
        'Semakin tinggi dan berat sebuah bangunan, semakin dalam asasnya perlu untuk memegangnya.'),
      m('Rina meletakkan buku berat di atas menara kertas. Menara runtuh. Apakah masalahnya?', ['Bahan terlalu lemah untuk berat itu', 'Buku terlalu berwarna', 'Menara terlalu pendek', 'Kertas terlalu putih'], 0,
        'Kertas tidak mampu menanggung berat buku, jadi struktur gagal.'),
      m('Manakah cara terbaik menjadikan menara blok lebih stabil?', ['Buat tapak lebih lebar', 'Buat lebih tinggi', 'Buat lebih kurus', 'Letak di tempat licin'], 0,
        'Tapak lebar merendahkan risiko tumbang. Tiga pilihan lain menjadikannya lebih goyah.'),
      m('Kenapa rumah di kawasan banjir dibina di atas tiang tinggi?', ['Supaya air tidak masuk ke dalam rumah', 'Supaya nampak cantik', 'Supaya angin masuk', 'Supaya rumah ringan'], 0,
        'Lantai yang tinggi berada di atas paras air banjir.')
    ],
    cabaran: [
      m('Ali membina jambatan kertas. Bagaimana dia boleh menguatkannya tanpa menambah kertas?', ['Lipat kertas menjadi bentuk beralun', 'Basahkan kertas', 'Potong kertas kecil', 'Cat kertas itu'], 0,
        'Lipatan mengubah kertas rata menjadi bentuk yang menahan lenturan, jadi ia jauh lebih kuat.'),
      i('Sebuah menara mempunyai 6 tingkat. Setiap tingkat menggunakan 12 blok. Berapa blok semuanya?', 72,
        '6 × 12 = 72 blok.'),
      m('Kenapa kaki kerusi selalunya empat dan bukan tiga?', ['Empat kaki mengedarkan berat dengan lebih rata', 'Tiga kaki terlalu mahal', 'Empat kaki lebih ringan', 'Tiga kaki terlalu tinggi'], 0,
        'Empat kaki memberi tapak yang lebih luas dan sokongan yang lebih rata di bawah orang yang duduk.'),
      m('Sebuah menara tinggi berdiri di kawasan berangin. Ciri manakah paling penting?', ['Tapak yang lebar dan berat di bawah', 'Warna yang cerah', 'Bumbung yang licin', 'Tingkap yang banyak'], 0,
        'Angin menolak menara dari tepi, jadi tapak lebar dan berat rendah menghalangnya daripada tumbang.'),
      i('Sebuah jambatan memerlukan 9 tiang. Setiap tiang menggunakan 15 batu bata. Berapa batu bata semuanya?', 135,
        '9 × 15 = 135 batu bata.'),
      m('Kenapa struktur bulat seperti terowong kuat menahan tekanan?', ['Bentuk melengkung menyebarkan daya ke seluruh permukaan', 'Bulat lebih ringan', 'Bulat lebih murah', 'Bulat lebih cantik'], 0,
        'Lengkungan menghantar daya ke tepi dan bukan menumpukannya pada satu titik.'),
      m('Manakah struktur yang paling mudah runtuh?', ['Tinggi, kurus dan bertapak sempit', 'Rendah, lebar dan berat', 'Segi tiga yang kukuh', 'Bertapak lebar dan pendek'], 0,
        'Tinggi menaikkan pusat berat, kurus mengurangkan kekuatan, dan tapak sempit menghilangkan kestabilan.'),
      m('Rina mahu menguji jambatan mana lebih kuat. Apakah yang MESTI sama?', ['Panjang jambatan dan cara beban diletakkan', 'Warna jambatan', 'Nama jambatan', 'Masa ujian sahaja'], 0,
        'Kalau panjang atau cara meletak beban berbeza, kita tidak tahu sama ada perbezaan datang daripada struktur atau daripada ujian itu sendiri.'),
      m('Kenapa binaan menggunakan gabungan bahan dan bukan satu bahan sahaja?', ['Setiap bahan kuat pada perkara yang berbeza', 'Supaya lebih berwarna', 'Supaya lebih murah sahaja', 'Supaya lebih berat'], 0,
        'Konkrit kuat menahan himpitan, besi kuat menahan tarikan. Digabungkan, struktur menjadi kuat dalam kedua-dua keadaan.'),
      m('Apakah yang paling mungkin berlaku kepada bangunan yang asasnya terlalu cetek?', ['Ia condong atau runtuh lama-kelamaan', 'Ia menjadi tinggi', 'Ia menjadi sejuk', 'Ia menjadi ringan'], 0,
        'Asas cetek tidak memegang bangunan dengan kukuh, jadi tanah di bawahnya mengalah sedikit demi sedikit.')
    ],
    ultra: [
      m('Dua menara dibina sama tinggi dengan blok yang sama banyak. Menara A lebar di bawah dan kurus di atas. Menara B kurus di bawah dan lebar di atas. Manakah lebih stabil?', ['Menara A, kerana beratnya berada di bawah', 'Menara B, kerana beratnya di atas', 'Kedua-duanya sama', 'Bergantung pada warna blok'], 0,
        'Berat yang rendah menjadikan menara sukar terbalik. Berat di atas menjadikannya mudah tumbang.'),
      i('Sebuah bangunan ada 12 tingkat. Setiap tingkat memerlukan 8 tiang. Sebanyak 5 tiang rosak dan diganti. Berapa jumlah tiang dalam bangunan itu?', 96,
        'Jumlah tiang = 12 × 8 = 96. Menggantikan tiang tidak menambah bilangannya.'),
      m('Kenapa jambatan panjang dibina dengan banyak segi tiga besi?', ['Segi tiga menahan bentuk walaupun beban berubah', 'Segi tiga lebih murah', 'Segi tiga lebih ringan sahaja', 'Segi tiga lebih senang dicat'], 0,
        'Kenderaan yang lalu mengubah beban sepanjang masa. Segi tiga tidak berubah bentuk, jadi jambatan kekal selamat.'),
      m('Sebuah rak buku goyang apabila disentuh. Apakah pembaikan yang PALING berkesan?', ['Tambah palang serong di belakang', 'Cat rak itu', 'Tambah buku di atas', 'Alihkan ke tempat lain'], 0,
        'Palang serong menjadikan bentuk segi empat itu dua segi tiga, dan segi tiga tidak senget.'),
      i('Sebuah menara memerlukan 25 blok setiap tingkat. Ali ada 180 blok. Berapa tingkat penuh yang boleh dia bina?', 7,
        '180 ÷ 25 = 7 tingkat penuh, dengan baki 5 blok.'),
      m('Kenapa bangunan tinggi direka supaya boleh bergoyang sedikit dalam angin kuat?', ['Struktur yang langsung tidak boleh bergerak akan patah', 'Supaya orang di dalam berasa seronok', 'Supaya bangunan ringan', 'Supaya bangunan cantik'], 0,
        'Bahan yang terlalu tegar akan retak. Sedikit lenturan menyerap daya angin tanpa merosakkan struktur.'),
      m('Manakah kesimpulan yang PALING tepat tentang kekuatan binaan?', ['Kekuatan bergantung pada bahan dan bentuk, bukan satu sahaja', 'Hanya bahan yang penting', 'Hanya bentuk yang penting', 'Hanya saiz yang penting'], 0,
        'Bahan kuat dalam bentuk yang lemah tetap runtuh, dan bentuk kuat daripada bahan lemah juga runtuh.'),
      m('Kenapa rumah tradisional Melayu dibina di atas tiang?', ['Mengelak banjir dan membenarkan udara mengalir di bawah', 'Supaya nampak tinggi', 'Supaya senang dicat', 'Supaya ringan'], 0,
        'Tiang mengangkat lantai di atas air banjir, dan ruang di bawah membenarkan angin lalu menyejukkan rumah.'),
      i('Sebuah jambatan mainan runtuh pada beban 240 g. Selepas ditambah palang segi tiga, ia menanggung 3 kali ganda. Berapa gram beban yang boleh ditanggung sekarang?', 720,
        '3 × 240 = 720 g.'),
      m('Seorang murid berkata "menara paling tinggi mesti paling kuat." Apakah kesilapannya?', ['Ketinggian tidak menentukan kekuatan; tapak dan bahan yang menentukan', 'Menara tinggi memang selalu lemah', 'Ketinggian tidak boleh diukur', 'Menara pendek tidak berguna'], 0,
        'Menara tinggi yang bertapak sempit sangat mudah tumbang. Kekuatan datang daripada tapak, bahan dan bentuk.')
    ]
  }
];
